/** Generated by itemis CREATE code generator. */


#ifndef ACTIVE_SYSTEMS_COUNTERTRACER_H_
#define ACTIVE_SYSTEMS_COUNTERTRACER_H_


#include "../src/yet_sc_tracer.h"


#include "Active_Systems_Counter.h"
#include "Active_Systems_Counter_meta.h"


#ifdef __cplusplus
extern "C"
{
#endif


extern void active_Systems_Counter_init_sc_tracer(yet_sc_tracer *tracer, Active_Systems_Counter* machine, sc_string name);


#ifdef __cplusplus
}
#endif


#endif /* ACTIVE_SYSTEMS_COUNTERTRACER_H_ */
