/** Generated by itemis CREATE code generator. */

#include "TV_Unit_meta.h"
		
sc_string TV_Unit_meta_feature_names[] = {
	"<nothing>",
	"change",
	"channel",
	"device.on",
	"device.off",
	"device.isOn",
	"input.source",
	"input.toggle",
	"input.satellite",
	"input.cable",
	"input.hdmi"
};

sc_string TV_Unit_meta_state_names[] = {
	"<nostate>",
	"_TV_Unit_._TV_On_",
	"_TV_Unit_._TV_On_._TV_Working_.satelliteTV",
	"_TV_Unit_._TV_On_._TV_Working_.satelliteTV._Changing_Channel_.changeChannel",
	"_TV_Unit_._TV_On_._TV_Working_.cable",
	"_TV_Unit_._TV_On_._TV_Working_.hdmi",
	"_TV_Unit_._TV_onSleep_"
};
