/** Generated by itemis CREATE code generator. */
package smarthub.java;

import com.yakindu.core.IEventDriven;
import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import smarthub.java.Actuator_Component;
import smarthub.java.Controller_Component;
import smarthub.java.DeviceTemp_Component;
import smarthub.java.Network_Component;
import smarthub.java.Power_Component;
import smarthub.java.Sensor_Component;
import smarthub.java.TV_Unit;

public class SmartTVSystem implements IStatemachine, ITimed, IEventDriven {
	public static class System {
		private SmartTVSystem parent;
		
		public System(SmartTVSystem parent) {
			this.parent = parent;
		}
		private boolean on;
		
		
		public void raiseOn() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					on = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean off;
		
		
		public void raiseOff() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					off = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean connect_network;
		
		
		public void raiseConnect_network() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					connect_network = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean disconnect_network;
		
		
		public void raiseDisconnect_network() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					disconnect_network = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean isOn;
		
		public synchronized boolean getIsOn() {
			synchronized(parent) {
				return isOn;
			}
		}
		
		public void setIsOn(boolean value) {
			synchronized(parent) {
				this.isOn = value;
			}
		}
		
	}
	
	public static class SensorInput {
		private SmartTVSystem parent;
		
		public SensorInput(SmartTVSystem parent) {
			this.parent = parent;
		}
		private long detection_time;
		
		public synchronized long getDetection_time() {
			synchronized(parent) {
				return detection_time;
			}
		}
		
		public void setDetection_time(long value) {
			synchronized(parent) {
				this.detection_time = value;
			}
		}
		
		private long timeout_time;
		
		public synchronized long getTimeout_time() {
			synchronized(parent) {
				return timeout_time;
			}
		}
		
		public void setTimeout_time(long value) {
			synchronized(parent) {
				this.timeout_time = value;
			}
		}
		
	}
	
	public static class SensorOutput {
		private SmartTVSystem parent;
		
		public SensorOutput(SmartTVSystem parent) {
			this.parent = parent;
		}
		private long counter;
		
		public synchronized long getCounter() {
			synchronized(parent) {
				return counter;
			}
		}
		
		public void setCounter(long value) {
			synchronized(parent) {
				this.counter = value;
			}
		}
		
		private boolean activity;
		
		public synchronized boolean getActivity() {
			synchronized(parent) {
				return activity;
			}
		}
		
		public void setActivity(boolean value) {
			synchronized(parent) {
				this.activity = value;
			}
		}
		
	}
	
	protected System system;
	
	protected SensorInput sensorInput;
	
	protected SensorOutput sensorOutput;
	
	public enum State {
		_SMARTTVSYSTEM__SMARTTVSYSTEM,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_OFF,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_ON,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT_OFF,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT_OFF,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT_OFF,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT_OFF,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT_OFF,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_,
		_SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE_OFF,
		$NULLSTATE$
	};
	
	private final State[] stateVector = new State[7];
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[7];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		synchronized(SmartTVSystem.this) {
			return isExecuting;
		}
	}
	
	protected void setIsExecuting(boolean value) {
		synchronized(SmartTVSystem.this) {
			this.isExecuting = value;
		}
	}
	private long stateConfVectorPosition;
	
	protected long getStateConfVectorPosition() {
		synchronized(SmartTVSystem.this) {
			return stateConfVectorPosition;
		}
	}
	
	protected void setStateConfVectorPosition(long value) {
		synchronized(SmartTVSystem.this) {
			this.stateConfVectorPosition = value;
		}
	}
	public SmartTVSystem() {
		system = new System(this);
		sensorInput = new SensorInput(this);
		sensorOutput = new SensorOutput(this);
		for (int i = 0; i < 7; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		/* Default init sequence for statechart SmartTVSystem */
		setActuator(null);
		setController(null);
		setSensor(null);
		setWiFi(null);
		setPower(null);
		setTemp(null);
		setTV(null);
		setMessage("");
		setWiFi_connection(false);
		setTemp_value(50l);
		setPower_input(50l);
		setPower_total(0l);
		setPower_required(10l);
		system.setIsOn(false);
		sensorInput.setDetection_time(5l);
		sensorInput.setTimeout_time(8l);
		sensorOutput.setCounter(0l);
		sensorOutput.setActivity(false);
		
		isExecuting = false;
	}
	
	public synchronized void enter() {
		/* Activates the state machine. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		if (getIsExecuting()) {
			return
			;
		}
		isExecuting = true;
		/* Default enter sequence for statechart SmartTVSystem */
		enterSequence__SmartTVSystem__default();
		isExecuting = false;
	}
	
	public synchronized void exit() {
		/* Deactivates the state machine. */
		if (getIsExecuting()) {
			return
			;
		}
		isExecuting = true;
		/* Default exit sequence for statechart SmartTVSystem */
		exitSequence__SmartTVSystem_();
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$||stateVector[1] != State.$NULLSTATE$||stateVector[2] != State.$NULLSTATE$||stateVector[3] != State.$NULLSTATE$||stateVector[4] != State.$NULLSTATE$||stateVector[5] != State.$NULLSTATE$||stateVector[6] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	private void clearInEvents() {
		system.on = false;
		system.off = false;
		system.connect_network = false;
		system.disconnect_network = false;
		timeEvents[0] = false;
		timeEvents[1] = false;
		timeEvents[2] = false;
		timeEvents[3] = false;
		timeEvents[4] = false;
		timeEvents[5] = false;
		timeEvents[6] = false;
	}
	
	private void microStep() {
		long transitioned = -1l;
		stateConfVectorPosition = 0l;
		switch (stateVector[0]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_OFF:
			transitioned = _SmartTVSystem__SmartTVSystem_SystemStatus_off_react(transitioned);
			break;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_ON:
			transitioned = _SmartTVSystem__SmartTVSystem_SystemStatus_on_react(transitioned);
			break;
		default:
			break;
		}
		if (getStateConfVectorPosition()<1l) {
			switch (stateVector[1]) {
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_:
				transitioned = _SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates__react(transitioned);
				break;
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_:
				transitioned = _SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning__react(transitioned);
				break;
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT_OFF:
				transitioned = _SmartTVSystem__SmartTVSystem_ActuatorComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<2l) {
			switch (stateVector[2]) {
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_:
				transitioned = _SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates__react(transitioned);
				break;
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT_OFF:
				transitioned = _SmartTVSystem__SmartTVSystem_ControllerComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<3l) {
			switch (stateVector[3]) {
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_:
				transitioned = _SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates__react(transitioned);
				break;
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT_OFF:
				transitioned = _SmartTVSystem__SmartTVSystem_SensorComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<4l) {
			switch (stateVector[4]) {
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_:
				transitioned = _SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates__react(transitioned);
				break;
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT_OFF:
				transitioned = _SmartTVSystem__SmartTVSystem_NetworkComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<5l) {
			switch (stateVector[5]) {
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_:
				transitioned = _SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates__react(transitioned);
				break;
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT_OFF:
				transitioned = _SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<6l) {
			switch (stateVector[6]) {
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_:
				_SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates__react(transitioned);
				break;
			case _SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE_OFF:
				_SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_off_react(transitioned);
				break;
			default:
				break;
			}
		}
	}
	
	private void runCycle() {
		/* Performs a 'run to completion' step. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		if (getIsExecuting()) {
			return
			;
		}
		isExecuting = true;
		nextEvent();
		do { 
			microStep();
			clearInEvents();
		} while (nextEvent());
		isExecuting = false;
	}
	
	protected boolean nextEvent() {
		if(!inEventQueue.isEmpty()) {
			inEventQueue.poll().run();
			return true;
		}
		return false;
	}
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM:
			return stateVector[0].ordinal() >= State.
					_SMARTTVSYSTEM__SMARTTVSYSTEM.ordinal()&& stateVector[0].ordinal() <= State._SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE_OFF.ordinal();
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_OFF:
			return stateVector[0] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_OFF;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_ON:
			return stateVector[0] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_ON;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_:
			return stateVector[1] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_:
			return stateVector[1] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT_OFF:
			return stateVector[1] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT_OFF;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT_:
			return stateVector[2].ordinal() >= State.
					_SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT_.ordinal()&& stateVector[2].ordinal() <= State._SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_.ordinal();
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_:
			return stateVector[2] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT_OFF:
			return stateVector[2] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT_OFF;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT_:
			return stateVector[3].ordinal() >= State.
					_SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT_.ordinal()&& stateVector[3].ordinal() <= State._SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_.ordinal();
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_:
			return stateVector[3] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT_OFF:
			return stateVector[3] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT_OFF;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT_:
			return stateVector[4].ordinal() >= State.
					_SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT_.ordinal()&& stateVector[4].ordinal() <= State._SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_.ordinal();
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_:
			return stateVector[4] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT_OFF:
			return stateVector[4] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT_OFF;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT_:
			return stateVector[5].ordinal() >= State.
					_SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT_.ordinal()&& stateVector[5].ordinal() <= State._SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_.ordinal();
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_:
			return stateVector[5] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT_OFF:
			return stateVector[5] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT_OFF;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT_:
			return stateVector[6].ordinal() >= State.
					_SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT_.ordinal()&& stateVector[6].ordinal() <= State._SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_.ordinal();
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_:
			return stateVector[6] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE_OFF:
			return stateVector[6] == State._SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE_OFF;
		default:
			return false;
		}
	}
	
	public synchronized void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public synchronized void raiseTimeEvent(int eventID) {
		inEventQueue.add(() -> {
			timeEvents[eventID] = true;
		});
		runCycle();
	}
	
	public System system() {
		return system;
	}
	
	public SensorInput sensorInput() {
		return sensorInput;
	}
	
	public SensorOutput sensorOutput() {
		return sensorOutput;
	}
	
	
	private Actuator_Component actuator;
	
	public synchronized Actuator_Component getActuator() {
		synchronized(SmartTVSystem.this) {
			return actuator;
		}
	}
	
	public void setActuator(Actuator_Component value) {
		synchronized(SmartTVSystem.this) {
			this.actuator = value;
		}
	}
	
	private Controller_Component controller;
	
	public synchronized Controller_Component getController() {
		synchronized(SmartTVSystem.this) {
			return controller;
		}
	}
	
	public void setController(Controller_Component value) {
		synchronized(SmartTVSystem.this) {
			this.controller = value;
		}
	}
	
	private Sensor_Component sensor;
	
	public synchronized Sensor_Component getSensor() {
		synchronized(SmartTVSystem.this) {
			return sensor;
		}
	}
	
	public void setSensor(Sensor_Component value) {
		synchronized(SmartTVSystem.this) {
			this.sensor = value;
		}
	}
	
	private Network_Component wiFi;
	
	public synchronized Network_Component getWiFi() {
		synchronized(SmartTVSystem.this) {
			return wiFi;
		}
	}
	
	public void setWiFi(Network_Component value) {
		synchronized(SmartTVSystem.this) {
			this.wiFi = value;
		}
	}
	
	private Power_Component power;
	
	public synchronized Power_Component getPower() {
		synchronized(SmartTVSystem.this) {
			return power;
		}
	}
	
	public void setPower(Power_Component value) {
		synchronized(SmartTVSystem.this) {
			this.power = value;
		}
	}
	
	private DeviceTemp_Component temp;
	
	public synchronized DeviceTemp_Component getTemp() {
		synchronized(SmartTVSystem.this) {
			return temp;
		}
	}
	
	public void setTemp(DeviceTemp_Component value) {
		synchronized(SmartTVSystem.this) {
			this.temp = value;
		}
	}
	
	private TV_Unit tV;
	
	public synchronized TV_Unit getTV() {
		synchronized(SmartTVSystem.this) {
			return tV;
		}
	}
	
	public void setTV(TV_Unit value) {
		synchronized(SmartTVSystem.this) {
			this.tV = value;
		}
	}
	
	private String message;
	
	public synchronized String getMessage() {
		synchronized(SmartTVSystem.this) {
			return message;
		}
	}
	
	public void setMessage(String value) {
		synchronized(SmartTVSystem.this) {
			this.message = value;
		}
	}
	
	private boolean wiFi_connection;
	
	public synchronized boolean getWiFi_connection() {
		synchronized(SmartTVSystem.this) {
			return wiFi_connection;
		}
	}
	
	public void setWiFi_connection(boolean value) {
		synchronized(SmartTVSystem.this) {
			this.wiFi_connection = value;
		}
	}
	
	private long temp_value;
	
	public synchronized long getTemp_value() {
		synchronized(SmartTVSystem.this) {
			return temp_value;
		}
	}
	
	public void setTemp_value(long value) {
		synchronized(SmartTVSystem.this) {
			this.temp_value = value;
		}
	}
	
	private long power_input;
	
	public synchronized long getPower_input() {
		synchronized(SmartTVSystem.this) {
			return power_input;
		}
	}
	
	public void setPower_input(long value) {
		synchronized(SmartTVSystem.this) {
			this.power_input = value;
		}
	}
	
	private long power_total;
	
	public synchronized long getPower_total() {
		synchronized(SmartTVSystem.this) {
			return power_total;
		}
	}
	
	public void setPower_total(long value) {
		synchronized(SmartTVSystem.this) {
			this.power_total = value;
		}
	}
	
	private long power_required;
	
	public synchronized long getPower_required() {
		synchronized(SmartTVSystem.this) {
			return power_required;
		}
	}
	
	public void setPower_required(long value) {
		synchronized(SmartTVSystem.this) {
			this.power_required = value;
		}
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_SystemStatus_off() {
		/* Entry action for state 'off'. */
		system.setIsOn(false);
		system.raiseConnect_network();
		getPower().raiseOff();
		getSensor().raiseOff();
	}
	
	/* Entry action for state 'on'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_SystemStatus_on() {
		/* Entry action for state 'on'. */
		timerService.setTimer(this, 0, 1000l, false);
		system.setIsOn(true);
		getPower().raiseOn();
		getSensor().raiseOn();
	}
	
	/* Entry action for state '<Actuator_Updates>'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates_() {
		/* Entry action for state '<Actuator_Updates>'. */
		timerService.setTimer(this, 1, 200l, false);
		actuator.power().setDeviceInput(power_input);
	}
	
	/* Entry action for state '<Device_Functioning>'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning_() {
		/* Entry action for state '<Device_Functioning>'. */
		if (!getActuator().device().getActuated()) {
			setMessage("Smart devices main function is here");
		}
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_ActuatorComponent_off() {
		/* Entry action for state 'off'. */
		getActuator().raiseOff();
		actuator.power().setRequired(power_required);
	}
	
	/* Entry action for state '<Controller_Updates>'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_() {
		/* Entry action for state '<Controller_Updates>'. */
		timerService.setTimer(this, 2, 100l, false);
		controller.sensors().setTriggered(sensorOutput.activity);
		controller.setActivity(sensorOutput.activity);
		actuator.setIsTriggered(controller.actuator().getTriggered());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_ControllerComponent_off() {
		/* Entry action for state 'off'. */
		getController().raiseOff();
	}
	
	/* Entry action for state '<Sensor_Updates>'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_() {
		/* Entry action for state '<Sensor_Updates>'. */
		timerService.setTimer(this, 3, 100l, false);
		sensorOutput.setActivity(sensor.getActivity());
		sensorOutput.setCounter(sensor.getCounter());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_SensorComponent_off() {
		/* Entry action for state 'off'. */
		getSensor().raiseOff();
	}
	
	/* Entry action for state '<WiFi_Updates>'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_() {
		/* Entry action for state '<WiFi_Updates>'. */
		timerService.setTimer(this, 4, 1000l, false);
		setWiFi_connection(wiFi.getConnection());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_NetworkComponent_off() {
		/* Entry action for state 'off'. */
		getWiFi().raiseOff();
	}
	
	/* Entry action for state '<Power_Updates>'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_() {
		/* Entry action for state '<Power_Updates>'. */
		timerService.setTimer(this, 5, 1000l, false);
		power.device().setIsOn(system.isOn);
		power.setKilowatt(power_input);
		setPower_total(power.getKilowatt());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off() {
		/* Entry action for state 'off'. */
		getPower().raiseOff();
	}
	
	/* Entry action for state '<Temperature_Updates>'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_() {
		/* Entry action for state '<Temperature_Updates>'. */
		timerService.setTimer(this, 6, 1000l, false);
		setTemp_value(temp.heat().getLevel());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_off() {
		/* Entry action for state 'off'. */
		temp.device().setIsOn(system.isOn);
	}
	
	/* Exit action for state 'on'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_SystemStatus_on() {
		/* Exit action for state 'on'. */
		timerService.unsetTimer(this, 0);
	}
	
	/* Exit action for state '<Actuator_Updates>'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates_() {
		/* Exit action for state '<Actuator_Updates>'. */
		timerService.unsetTimer(this, 1);
	}
	
	/* Exit action for state '<Device_Functioning>'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning_() {
		/* Exit action for state '<Device_Functioning>'. */
		tV.device().setIsOn(false);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_ActuatorComponent_off() {
		/* Exit action for state 'off'. */
		getActuator().raiseOn();
	}
	
	/* Exit action for state '<Controller_Updates>'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_() {
		/* Exit action for state '<Controller_Updates>'. */
		timerService.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_ControllerComponent_off() {
		/* Exit action for state 'off'. */
		getController().raiseOn();
	}
	
	/* Exit action for state '<Sensor_Updates>'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_() {
		/* Exit action for state '<Sensor_Updates>'. */
		timerService.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_SensorComponent_off() {
		/* Exit action for state 'off'. */
		getSensor().raiseOn();
	}
	
	/* Exit action for state '<WiFi_Updates>'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_() {
		/* Exit action for state '<WiFi_Updates>'. */
		timerService.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_NetworkComponent_off() {
		/* Exit action for state 'off'. */
		getWiFi().raiseOn();
	}
	
	/* Exit action for state '<Power_Updates>'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_() {
		/* Exit action for state '<Power_Updates>'. */
		timerService.unsetTimer(this, 5);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off() {
		/* Exit action for state 'off'. */
		getPower().raiseOn();
	}
	
	/* Exit action for state '<Temperature_Updates>'. */
	private void exitAction__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_() {
		/* Exit action for state '<Temperature_Updates>'. */
		timerService.unsetTimer(this, 6);
	}
	
	/* 'default' enter sequence for state SmartTVSystem */
	private void enterSequence__SmartTVSystem__SmartTVSystem_default() {
		/* 'default' enter sequence for state SmartTVSystem */
		enterSequence__SmartTVSystem__SmartTVSystem_SystemStatus_default();
		enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent_default();
		enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent_default();
		enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent_default();
		enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent_default();
		enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_default();
		enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_default();
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartTVSystem__SmartTVSystem_SystemStatus_off_default() {
		/* 'default' enter sequence for state off */
		entryAction__SmartTVSystem__SmartTVSystem_SystemStatus_off();
		stateVector[0] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_OFF;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state on */
	private void enterSequence__SmartTVSystem__SmartTVSystem_SystemStatus_on_default() {
		/* 'default' enter sequence for state on */
		entryAction__SmartTVSystem__SmartTVSystem_SystemStatus_on();
		stateVector[0] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_ON;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state <Actuator_Updates> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates__default() {
		/* 'default' enter sequence for state <Actuator_Updates> */
		entryAction__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates_();
		stateVector[1] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state <Device_Functioning> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning__default() {
		/* 'default' enter sequence for state <Device_Functioning> */
		entryAction__SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning_();
		stateVector[1] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction__SmartTVSystem__SmartTVSystem_ActuatorComponent_off();
		stateVector[1] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT_OFF;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state <Initialize_Controller_Component> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__default() {
		/* 'default' enter sequence for state <Initialize_Controller_Component> */
		enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating_default();
	}
	
	/* 'default' enter sequence for state <Controller_Updates> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates__default() {
		/* 'default' enter sequence for state <Controller_Updates> */
		entryAction__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_();
		stateVector[2] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction__SmartTVSystem__SmartTVSystem_ControllerComponent_off();
		stateVector[2] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT_OFF;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state <Initialize_Sensor_Component> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__default() {
		/* 'default' enter sequence for state <Initialize_Sensor_Component> */
		enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating_default();
	}
	
	/* 'default' enter sequence for state <Sensor_Updates> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates__default() {
		/* 'default' enter sequence for state <Sensor_Updates> */
		entryAction__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_();
		stateVector[3] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction__SmartTVSystem__SmartTVSystem_SensorComponent_off();
		stateVector[3] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT_OFF;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state <Initialize_WiFi_Component> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__default() {
		/* 'default' enter sequence for state <Initialize_WiFi_Component> */
		enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating_default();
	}
	
	/* 'default' enter sequence for state <WiFi_Updates> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates__default() {
		/* 'default' enter sequence for state <WiFi_Updates> */
		entryAction__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_();
		stateVector[4] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_;
		stateConfVectorPosition = 4;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction__SmartTVSystem__SmartTVSystem_NetworkComponent_off();
		stateVector[4] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT_OFF;
		stateConfVectorPosition = 4;
	}
	
	/* 'default' enter sequence for state <Initialize_Power_Component> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__default() {
		/* 'default' enter sequence for state <Initialize_Power_Component> */
		enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating_default();
	}
	
	/* 'default' enter sequence for state <Power_Updates> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates__default() {
		/* 'default' enter sequence for state <Power_Updates> */
		entryAction__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_();
		stateVector[5] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_;
		stateConfVectorPosition = 5;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off_default() {
		/* 'default' enter sequence for state off */
		entryAction__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off();
		stateVector[5] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT_OFF;
		stateConfVectorPosition = 5;
	}
	
	/* 'default' enter sequence for state <Initialize_DeviceTemp_Component> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__default() {
		/* 'default' enter sequence for state <Initialize_DeviceTemp_Component> */
		enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating_default();
	}
	
	/* 'default' enter sequence for state <Temperature_Updates> */
	private void enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates__default() {
		/* 'default' enter sequence for state <Temperature_Updates> */
		entryAction__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_();
		stateVector[6] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_;
		stateConfVectorPosition = 6;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_off_default() {
		/* 'default' enter sequence for state off */
		entryAction__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_off();
		stateVector[6] = State._SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE_OFF;
		stateConfVectorPosition = 6;
	}
	
	/* 'default' enter sequence for region <SmartTVSystem> */
	private void enterSequence__SmartTVSystem__default() {
		/* 'default' enter sequence for region <SmartTVSystem> */
		react__SmartTVSystem___entry_Default();
	}
	
	/* 'default' enter sequence for region SystemStatus */
	private void enterSequence__SmartTVSystem__SmartTVSystem_SystemStatus_default() {
		/* 'default' enter sequence for region SystemStatus */
		react__SmartTVSystem__SmartTVSystem_SystemStatus__entry_Default();
	}
	
	/* 'default' enter sequence for region ActuatorComponent */
	private void enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent_default() {
		/* 'default' enter sequence for region ActuatorComponent */
		react__SmartTVSystem__SmartTVSystem_ActuatorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region ControllerComponent */
	private void enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent_default() {
		/* 'default' enter sequence for region ControllerComponent */
		react__SmartTVSystem__SmartTVSystem_ControllerComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region updating */
	private void enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating_default() {
		/* 'default' enter sequence for region updating */
		react__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__entry_Default();
	}
	
	/* 'default' enter sequence for region SensorComponent */
	private void enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent_default() {
		/* 'default' enter sequence for region SensorComponent */
		react__SmartTVSystem__SmartTVSystem_SensorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region updating */
	private void enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating_default() {
		/* 'default' enter sequence for region updating */
		react__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__entry_Default();
	}
	
	/* 'default' enter sequence for region NetworkComponent */
	private void enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent_default() {
		/* 'default' enter sequence for region NetworkComponent */
		react__SmartTVSystem__SmartTVSystem_NetworkComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region updating */
	private void enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating_default() {
		/* 'default' enter sequence for region updating */
		react__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__entry_Default();
	}
	
	/* 'default' enter sequence for region PowerCalculatorComponent */
	private void enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_default() {
		/* 'default' enter sequence for region PowerCalculatorComponent */
		react__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region updating */
	private void enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating_default() {
		/* 'default' enter sequence for region updating */
		react__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__entry_Default();
	}
	
	/* 'default' enter sequence for region trackingDeviceTemperature */
	private void enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_default() {
		/* 'default' enter sequence for region trackingDeviceTemperature */
		react__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__entry_Default();
	}
	
	/* 'default' enter sequence for region updating */
	private void enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating_default() {
		/* 'default' enter sequence for region updating */
		react__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__entry_Default();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartTVSystem__SmartTVSystem_SystemStatus_off() {
		/* Default exit sequence for state off */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state on */
	private void exitSequence__SmartTVSystem__SmartTVSystem_SystemStatus_on() {
		/* Default exit sequence for state on */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
		exitAction__SmartTVSystem__SmartTVSystem_SystemStatus_on();
	}
	
	/* Default exit sequence for state <Actuator_Updates> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates_() {
		/* Default exit sequence for state <Actuator_Updates> */
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
		exitAction__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates_();
	}
	
	/* Default exit sequence for state <Device_Functioning> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning_() {
		/* Default exit sequence for state <Device_Functioning> */
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
		exitAction__SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent_off() {
		/* Default exit sequence for state off */
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
		exitAction__SmartTVSystem__SmartTVSystem_ActuatorComponent_off();
	}
	
	/* Default exit sequence for state <Initialize_Controller_Component> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component_() {
		/* Default exit sequence for state <Initialize_Controller_Component> */
		exitSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating();
	}
	
	/* Default exit sequence for state <Controller_Updates> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_() {
		/* Default exit sequence for state <Controller_Updates> */
		stateVector[2] = State.$NULLSTATE$;
		stateConfVectorPosition = 2;
		exitAction__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartTVSystem__SmartTVSystem_ControllerComponent_off() {
		/* Default exit sequence for state off */
		stateVector[2] = State.$NULLSTATE$;
		stateConfVectorPosition = 2;
		exitAction__SmartTVSystem__SmartTVSystem_ControllerComponent_off();
	}
	
	/* Default exit sequence for state <Initialize_Sensor_Component> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component_() {
		/* Default exit sequence for state <Initialize_Sensor_Component> */
		exitSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating();
	}
	
	/* Default exit sequence for state <Sensor_Updates> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_() {
		/* Default exit sequence for state <Sensor_Updates> */
		stateVector[3] = State.$NULLSTATE$;
		stateConfVectorPosition = 3;
		exitAction__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartTVSystem__SmartTVSystem_SensorComponent_off() {
		/* Default exit sequence for state off */
		stateVector[3] = State.$NULLSTATE$;
		stateConfVectorPosition = 3;
		exitAction__SmartTVSystem__SmartTVSystem_SensorComponent_off();
	}
	
	/* Default exit sequence for state <Initialize_WiFi_Component> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component_() {
		/* Default exit sequence for state <Initialize_WiFi_Component> */
		exitSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating();
	}
	
	/* Default exit sequence for state <WiFi_Updates> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_() {
		/* Default exit sequence for state <WiFi_Updates> */
		stateVector[4] = State.$NULLSTATE$;
		stateConfVectorPosition = 4;
		exitAction__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartTVSystem__SmartTVSystem_NetworkComponent_off() {
		/* Default exit sequence for state off */
		stateVector[4] = State.$NULLSTATE$;
		stateConfVectorPosition = 4;
		exitAction__SmartTVSystem__SmartTVSystem_NetworkComponent_off();
	}
	
	/* Default exit sequence for state <Initialize_Power_Component> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component_() {
		/* Default exit sequence for state <Initialize_Power_Component> */
		exitSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating();
	}
	
	/* Default exit sequence for state <Power_Updates> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_() {
		/* Default exit sequence for state <Power_Updates> */
		stateVector[5] = State.$NULLSTATE$;
		stateConfVectorPosition = 5;
		exitAction__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off() {
		/* Default exit sequence for state off */
		stateVector[5] = State.$NULLSTATE$;
		stateConfVectorPosition = 5;
		exitAction__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off();
	}
	
	/* Default exit sequence for state <Initialize_DeviceTemp_Component> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component_() {
		/* Default exit sequence for state <Initialize_DeviceTemp_Component> */
		exitSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating();
	}
	
	/* Default exit sequence for state <Temperature_Updates> */
	private void exitSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_() {
		/* Default exit sequence for state <Temperature_Updates> */
		stateVector[6] = State.$NULLSTATE$;
		stateConfVectorPosition = 6;
		exitAction__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_off() {
		/* Default exit sequence for state off */
		stateVector[6] = State.$NULLSTATE$;
		stateConfVectorPosition = 6;
	}
	
	/* Default exit sequence for region <SmartTVSystem> */
	private void exitSequence__SmartTVSystem_() {
		/* Default exit sequence for region <SmartTVSystem> */
		switch (stateVector[0]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_OFF:
			exitSequence__SmartTVSystem__SmartTVSystem_SystemStatus_off();
			break;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SYSTEMSTATUS_ON:
			exitSequence__SmartTVSystem__SmartTVSystem_SystemStatus_on();
			break;
		default:
			break;
		}
		switch (stateVector[1]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_:
			exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates_();
			break;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_:
			exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning_();
			break;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_ACTUATORCOMPONENT_OFF:
			exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent_off();
			break;
		default:
			break;
		}
		switch (stateVector[2]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_:
			exitSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_();
			break;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT_OFF:
			exitSequence__SmartTVSystem__SmartTVSystem_ControllerComponent_off();
			break;
		default:
			break;
		}
		switch (stateVector[3]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_:
			exitSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_();
			break;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT_OFF:
			exitSequence__SmartTVSystem__SmartTVSystem_SensorComponent_off();
			break;
		default:
			break;
		}
		switch (stateVector[4]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_:
			exitSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_();
			break;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT_OFF:
			exitSequence__SmartTVSystem__SmartTVSystem_NetworkComponent_off();
			break;
		default:
			break;
		}
		switch (stateVector[5]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_:
			exitSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_();
			break;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT_OFF:
			exitSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off();
			break;
		default:
			break;
		}
		switch (stateVector[6]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_:
			exitSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_();
			break;
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE_OFF:
			exitSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_off();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region updating */
	private void exitSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating() {
		/* Default exit sequence for region updating */
		switch (stateVector[2]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_:
			exitSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region updating */
	private void exitSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating() {
		/* Default exit sequence for region updating */
		switch (stateVector[3]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_:
			exitSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region updating */
	private void exitSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating() {
		/* Default exit sequence for region updating */
		switch (stateVector[4]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_:
			exitSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region updating */
	private void exitSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating() {
		/* Default exit sequence for region updating */
		switch (stateVector[5]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_:
			exitSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region updating */
	private void exitSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating() {
		/* Default exit sequence for region updating */
		switch (stateVector[6]) {
		case _SMARTTVSYSTEM__SMARTTVSYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_:
			exitSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_SystemStatus__entry_Default() {
		/* Default react sequence for initial entry  */
		getTV().enter();
		enterSequence__SmartTVSystem__SmartTVSystem_SystemStatus_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_ActuatorComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getActuator().enter();
		enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_ControllerComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getController().enter();
		enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_SensorComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getSensor().enter();
		enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_NetworkComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getWiFi().enter();
		enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__entry_Default() {
		/* Default react sequence for initial entry  */
		getPower().enter();
		enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__entry_Default() {
		/* Default react sequence for initial entry  */
		getTemp().enter();
		enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartTVSystem___entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence__SmartTVSystem__SmartTVSystem_default();
	}
	
	private long react(long transitioned_before) {
		/* State machine reactions. */
		return transitioned_before
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_react(long transitioned_before) {
		/* The reactions of state SmartTVSystem. */
		long transitioned_after = transitioned_before;
		/* If no transition was taken then execute local reactions */
		transitioned_after = react(transitioned_before);
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_SystemStatus_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (system.on) {
				exitSequence__SmartTVSystem__SmartTVSystem_SystemStatus_off();
				enterSequence__SmartTVSystem__SmartTVSystem_SystemStatus_on_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_SystemStatus_on_react(long transitioned_before) {
		/* The reactions of state on. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (system.off) {
				exitSequence__SmartTVSystem__SmartTVSystem_SystemStatus_on();
				enterSequence__SmartTVSystem__SmartTVSystem_SystemStatus_off_default();
				transitioned_after = 0l;
			} else {
				if (timeEvents[0]) {
					exitSequence__SmartTVSystem__SmartTVSystem_SystemStatus_on();
					timeEvents[0] = false;
					enterSequence__SmartTVSystem__SmartTVSystem_SystemStatus_on_default();
					transitioned_after = 0l;
				}
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates__react(long transitioned_before) {
		/* The reactions of state <Actuator_Updates>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (getTV().device().getIsOn()) {
				exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates_();
				enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning__default();
				transitioned_after = 1l;
			} else {
				if (system.off) {
					exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates_();
					enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent_off_default();
					transitioned_after = 1l;
				} else {
					if (timeEvents[1]) {
						exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates_();
						timeEvents[1] = false;
						enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates__default();
						transitioned_after = 1l;
					}
				}
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning__react(long transitioned_before) {
		/* The reactions of state <Device_Functioning>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (getActuator().getIsTriggered()) {
				exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning_();
				sensor.setActivity(false);
				enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates__default();
				transitioned_after = 1l;
			} else {
				if (system.off) {
					exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Device_Functioning_();
					enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent_off_default();
					transitioned_after = 1l;
				}
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_ActuatorComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (system.on) {
				exitSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent_off();
				enterSequence__SmartTVSystem__SmartTVSystem_ActuatorComponent__Actuator_Updates__default();
				transitioned_after = 1l;
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__react(long transitioned_before) {
		/* The reactions of state <Initialize_Controller_Component>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (system.off) {
				exitSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component_();
				enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent_off_default();
				transitioned_after = 2l;
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates__react(long transitioned_before) {
		/* The reactions of state <Controller_Updates>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (timeEvents[2]) {
				exitSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_();
				timeEvents[2] = false;
				enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates__default();
				_SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__react(2l);
				transitioned_after = 2l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = _SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_ControllerComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (system.on) {
				exitSequence__SmartTVSystem__SmartTVSystem_ControllerComponent_off();
				enterSequence__SmartTVSystem__SmartTVSystem_ControllerComponent__Initialize_Controller_Component__default();
				transitioned_after = 2l;
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__react(long transitioned_before) {
		/* The reactions of state <Initialize_Sensor_Component>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (system.off) {
				exitSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component_();
				enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent_off_default();
				transitioned_after = 3l;
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates__react(long transitioned_before) {
		/* The reactions of state <Sensor_Updates>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (timeEvents[3]) {
				exitSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_();
				timeEvents[3] = false;
				enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates__default();
				_SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__react(3l);
				transitioned_after = 3l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = _SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_SensorComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (system.on) {
				exitSequence__SmartTVSystem__SmartTVSystem_SensorComponent_off();
				enterSequence__SmartTVSystem__SmartTVSystem_SensorComponent__Initialize_Sensor_Component__default();
				transitioned_after = 3l;
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__react(long transitioned_before) {
		/* The reactions of state <Initialize_WiFi_Component>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<4l) {
			if ((system.off || system.disconnect_network)) {
				exitSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component_();
				enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent_off_default();
				transitioned_after = 4l;
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates__react(long transitioned_before) {
		/* The reactions of state <WiFi_Updates>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<4l) {
			if (timeEvents[4]) {
				exitSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_();
				timeEvents[4] = false;
				enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates__default();
				_SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__react(4l);
				transitioned_after = 4l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = _SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_NetworkComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<4l) {
			if ((system.on || system.connect_network)) {
				exitSequence__SmartTVSystem__SmartTVSystem_NetworkComponent_off();
				enterSequence__SmartTVSystem__SmartTVSystem_NetworkComponent__Initialize_WiFi_Component__default();
				transitioned_after = 4l;
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__react(long transitioned_before) {
		/* The reactions of state <Initialize_Power_Component>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<5l) {
			if (system.off) {
				exitSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component_();
				enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off_default();
				transitioned_after = 5l;
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates__react(long transitioned_before) {
		/* The reactions of state <Power_Updates>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<5l) {
			if (timeEvents[5]) {
				exitSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_();
				timeEvents[5] = false;
				enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates__default();
				_SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__react(5l);
				transitioned_after = 5l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = _SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<5l) {
			if (system.on) {
				exitSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent_off();
				enterSequence__SmartTVSystem__SmartTVSystem_PowerCalculatorComponent__Initialize_Power_Component__default();
				transitioned_after = 5l;
			}
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__react(long transitioned_before) {
		/* The reactions of state <Initialize_DeviceTemp_Component>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<6l) {
			if (system.off) {
				exitSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component_();
				enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_off_default();
				_SmartTVSystem__SmartTVSystem_react(0l);
				transitioned_after = 6l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = _SmartTVSystem__SmartTVSystem_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates__react(long transitioned_before) {
		/* The reactions of state <Temperature_Updates>. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<6l) {
			if (timeEvents[6]) {
				exitSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_();
				timeEvents[6] = false;
				enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates__default();
				_SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__react(6l);
				transitioned_after = 6l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = _SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long _SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_off_react(long transitioned_before) {
		/* The reactions of state off. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<6l) {
			if (system.on) {
				exitSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature_off();
				enterSequence__SmartTVSystem__SmartTVSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__default();
				_SmartTVSystem__SmartTVSystem_react(0l);
				transitioned_after = 6l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = _SmartTVSystem__SmartTVSystem_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	/* Can be used by the client code to trigger a run to completion step without raising an event. */
	public synchronized void triggerWithoutEvent() {
		runCycle();
	}
}
