/** Generated by YAKINDU Statechart Tools code generator. */
package smarthub.java;

import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class Power_Component implements IStatemachine, ITimed {
	public static class Device {
		private Power_Component parent;
		
		public Device(Power_Component parent) {
			this.parent = parent;
		}
		private boolean isOn;
		
		public synchronized boolean getIsOn() {
			synchronized(parent) {
				return isOn;
			}
		}
		
		public void setIsOn(boolean value) {
			synchronized(parent) {
				this.isOn = value;
			}
		}
		
	}
	
	protected Device device;
	
	public enum State {
		MAIN_REGION_POWER_COMPONENT,
		MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_NOPOWERCONSUMED,
		MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_CONSUMING_POWER,
		$NULLSTATE$
	};
	
	private final State[] stateVector = new State[1];
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[1];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		synchronized(Power_Component.this) {
			return isExecuting;
		}
	}
	
	protected void setIsExecuting(boolean value) {
		synchronized(Power_Component.this) {
			this.isExecuting = value;
		}
	}
	public Power_Component() {
		device = new Device(this);
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		setKWh(0l);
		
		setKilowatt(20l);
		
		setHour(1l);
		
		setTotalPower(0l);
		
		setTotalHour(0l);
		
		device.setIsOn(false);
		
		isExecuting = false;
	}
	
	public synchronized void enter() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		enterSequence_main_region_default();
		isExecuting = false;
	}
	
	public synchronized void exit() {
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		exitSequence_main_region();
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	private void clearInEvents() {
		on = false;
		off = false;
		timeEvents[0] = false;
	}
	
	private void microStep() {
		switch (stateVector[0]) {
		case MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_NOPOWERCONSUMED:
			main_region_Power_Component_PowerConsumption_NoPowerConsumed_react(-1l);
			break;
		case MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_CONSUMING_POWER:
			main_region_Power_Component_PowerConsumption_consuming_power_react(-1l);
			break;
		default:
			break;
		}
	}
	
	private void runCycle() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		nextEvent();
		do { 
			microStep();
			
			clearInEvents();
			
			nextEvent();
		} while (((on || off) || timeEvents[0]));
		
		isExecuting = false;
	}
	
	protected void nextEvent() {
		if(!inEventQueue.isEmpty()) {
			inEventQueue.poll().run();
			return;
		}
	}
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case MAIN_REGION_POWER_COMPONENT:
			return stateVector[0].ordinal() >= State.
					MAIN_REGION_POWER_COMPONENT.ordinal()&& stateVector[0].ordinal() <= State.MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_CONSUMING_POWER.ordinal();
		case MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_NOPOWERCONSUMED:
			return stateVector[0] == State.MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_NOPOWERCONSUMED;
		case MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_CONSUMING_POWER:
			return stateVector[0] == State.MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_CONSUMING_POWER;
		default:
			return false;
		}
	}
	
	public synchronized void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public synchronized void raiseTimeEvent(int eventID) {
		inEventQueue.add(() -> {
			timeEvents[eventID] = true;
		});
		runCycle();
	}
	
	public Device device() {
		return device;
	}
	
	
	private boolean on;
	
	
	public void raiseOn() {
		synchronized(Power_Component.this) {
			inEventQueue.add(() -> {
				on = true;
			});
			runCycle();
		}
	}
	
	private boolean off;
	
	
	public void raiseOff() {
		synchronized(Power_Component.this) {
			inEventQueue.add(() -> {
				off = true;
			});
			runCycle();
		}
	}
	
	private long kWh;
	
	public synchronized long getKWh() {
		synchronized(Power_Component.this) {
			return kWh;
		}
	}
	
	public void setKWh(long value) {
		synchronized(Power_Component.this) {
			this.kWh = value;
		}
	}
	
	private long kilowatt;
	
	public synchronized long getKilowatt() {
		synchronized(Power_Component.this) {
			return kilowatt;
		}
	}
	
	public void setKilowatt(long value) {
		synchronized(Power_Component.this) {
			this.kilowatt = value;
		}
	}
	
	private long hour;
	
	public synchronized long getHour() {
		synchronized(Power_Component.this) {
			return hour;
		}
	}
	
	public void setHour(long value) {
		synchronized(Power_Component.this) {
			this.hour = value;
		}
	}
	
	private long totalPower;
	
	public synchronized long getTotalPower() {
		synchronized(Power_Component.this) {
			return totalPower;
		}
	}
	
	public void setTotalPower(long value) {
		synchronized(Power_Component.this) {
			this.totalPower = value;
		}
	}
	
	private long totalHour;
	
	public synchronized long getTotalHour() {
		synchronized(Power_Component.this) {
			return totalHour;
		}
	}
	
	public void setTotalHour(long value) {
		synchronized(Power_Component.this) {
			this.totalHour = value;
		}
	}
	
	/* Entry action for state 'NoPowerConsumed'. */
	private void entryAction_main_region_Power_Component_PowerConsumption_NoPowerConsumed() {
		setHour(0l);
	}
	
	/* Entry action for state 'consuming_power'. */
	private void entryAction_main_region_Power_Component_PowerConsumption_consuming_power() {
		timerService.setTimer(this, 0, (1l * 1000l), false);
		
		setKWh((kilowatt * hour));
		
		setTotalPower((kWh * totalHour));
	}
	
	/* Exit action for state 'consuming_power'. */
	private void exitAction_main_region_Power_Component_PowerConsumption_consuming_power() {
		timerService.unsetTimer(this, 0);
	}
	
	/* 'default' enter sequence for state Power_Component */
	private void enterSequence_main_region_Power_Component_default() {
		enterSequence_main_region_Power_Component_PowerConsumption_default();
	}
	
	/* 'default' enter sequence for state NoPowerConsumed */
	private void enterSequence_main_region_Power_Component_PowerConsumption_NoPowerConsumed_default() {
		entryAction_main_region_Power_Component_PowerConsumption_NoPowerConsumed();
		stateVector[0] = State.MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_NOPOWERCONSUMED;
	}
	
	/* 'default' enter sequence for state consuming_power */
	private void enterSequence_main_region_Power_Component_PowerConsumption_consuming_power_default() {
		entryAction_main_region_Power_Component_PowerConsumption_consuming_power();
		stateVector[0] = State.MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_CONSUMING_POWER;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* 'default' enter sequence for region PowerConsumption */
	private void enterSequence_main_region_Power_Component_PowerConsumption_default() {
		react_main_region_Power_Component_PowerConsumption__entry_Default();
	}
	
	/* Default exit sequence for state NoPowerConsumed */
	private void exitSequence_main_region_Power_Component_PowerConsumption_NoPowerConsumed() {
		stateVector[0] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state consuming_power */
	private void exitSequence_main_region_Power_Component_PowerConsumption_consuming_power() {
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_main_region_Power_Component_PowerConsumption_consuming_power();
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_NOPOWERCONSUMED:
			exitSequence_main_region_Power_Component_PowerConsumption_NoPowerConsumed();
			break;
		case MAIN_REGION_POWER_COMPONENT_POWERCONSUMPTION_CONSUMING_POWER:
			exitSequence_main_region_Power_Component_PowerConsumption_consuming_power();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_Power_Component_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region_Power_Component_PowerConsumption__entry_Default() {
		enterSequence_main_region_Power_Component_PowerConsumption_NoPowerConsumed_default();
	}
	
	private long react(long transitioned_before) {
		return transitioned_before;
	}
	
	private long main_region_Power_Component_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0l) {
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long main_region_Power_Component_PowerConsumption_NoPowerConsumed_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0l) {
			if (device.getIsOn()) {
				exitSequence_main_region_Power_Component_PowerConsumption_NoPowerConsumed();
				enterSequence_main_region_Power_Component_PowerConsumption_consuming_power_default();
				main_region_Power_Component_react(0l);
				
				transitioned_after = 0l;
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = main_region_Power_Component_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long main_region_Power_Component_PowerConsumption_consuming_power_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0l) {
			if (timeEvents[0]) {
				exitSequence_main_region_Power_Component_PowerConsumption_consuming_power();
				totalHour++;
				
				timeEvents[0] = false;
				enterSequence_main_region_Power_Component_PowerConsumption_consuming_power_default();
				main_region_Power_Component_react(0l);
				
				transitioned_after = 0l;
			} else {
				if (!device.getIsOn()) {
					exitSequence_main_region_Power_Component_PowerConsumption_consuming_power();
					enterSequence_main_region_Power_Component_PowerConsumption_NoPowerConsumed_default();
					main_region_Power_Component_react(0l);
					
					transitioned_after = 0l;
				}
			}
		}
		/* If no transition was taken then execute local reactions */
		if (transitioned_after==transitioned_before) {
			transitioned_after = main_region_Power_Component_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	/* Can be used by the client code to trigger a run to completion step without raising an event. */
	public synchronized void triggerWithoutEvent() {
		runCycle();
	}
}
