/** Generated by itemis CREATE code generator. */
package smarthub.java;

import com.yakindu.core.IEventDriven;
import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class Environment implements IStatemachine, ITimed, IEventDriven {
	public static class Clock {
		private Environment parent;
		
		public Clock(Environment parent) {
			this.parent = parent;
		}
		private boolean run;
		
		
		public void raiseRun() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					run = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean stop;
		
		
		public void raiseStop() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					stop = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean reset;
		
		
		public void raiseReset() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					reset = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean running;
		
		public synchronized boolean getRunning() {
			synchronized(parent) {
				return running;
			}
		}
		
		public void setRunning(boolean value) {
			synchronized(parent) {
				this.running = value;
			}
		}
		
		private long timeRunning;
		
		public synchronized long getTimeRunning() {
			synchronized(parent) {
				return timeRunning;
			}
		}
		
		public void setTimeRunning(long value) {
			synchronized(parent) {
				this.timeRunning = value;
			}
		}
		
	}
	
	public static class Simulator {
		private Environment parent;
		
		public Simulator(Environment parent) {
			this.parent = parent;
		}
		private boolean launch;
		
		
		public void raiseLaunch() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					launch = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean start;
		
		
		public void raiseStart() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					start = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean terminate;
		
		
		public void raiseTerminate() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					terminate = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean cycle;
		
		
		public void raiseCycle() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					cycle = true;
				});
				parent.runCycle();
			}
		}
		
		private long randomVal;
		
		public synchronized long getRandomVal() {
			synchronized(parent) {
				return randomVal;
			}
		}
		
		public void setRandomVal(long value) {
			synchronized(parent) {
				this.randomVal = value;
			}
		}
		
		private boolean processing;
		
		public synchronized boolean getProcessing() {
			synchronized(parent) {
				return processing;
			}
		}
		
		public void setProcessing(boolean value) {
			synchronized(parent) {
				this.processing = value;
			}
		}
		
		private boolean reading;
		
		public synchronized boolean getReading() {
			synchronized(parent) {
				return reading;
			}
		}
		
		public void setReading(boolean value) {
			synchronized(parent) {
				this.reading = value;
			}
		}
		
		private boolean generating;
		
		public synchronized boolean getGenerating() {
			synchronized(parent) {
				return generating;
			}
		}
		
		public void setGenerating(boolean value) {
			synchronized(parent) {
				this.generating = value;
			}
		}
		
		private boolean terminated;
		
		public synchronized boolean getTerminated() {
			synchronized(parent) {
				return terminated;
			}
		}
		
		public void setTerminated(boolean value) {
			synchronized(parent) {
				this.terminated = value;
			}
		}
		
		private boolean booleanOutput;
		
		public synchronized boolean getBooleanOutput() {
			synchronized(parent) {
				return booleanOutput;
			}
		}
		
		public void setBooleanOutput(boolean value) {
			synchronized(parent) {
				this.booleanOutput = value;
			}
		}
		
		private long numericalOutput;
		
		public synchronized long getNumericalOutput() {
			synchronized(parent) {
				return numericalOutput;
			}
		}
		
		public void setNumericalOutput(long value) {
			synchronized(parent) {
				this.numericalOutput = value;
			}
		}
		
	}
	
	public static class Time {
		private Environment parent;
		
		public Time(Environment parent) {
			this.parent = parent;
		}
		private long process;
		
		public synchronized long getProcess() {
			synchronized(parent) {
				return process;
			}
		}
		
		public void setProcess(long value) {
			synchronized(parent) {
				this.process = value;
			}
		}
		
		private long read;
		
		public synchronized long getRead() {
			synchronized(parent) {
				return read;
			}
		}
		
		public void setRead(long value) {
			synchronized(parent) {
				this.read = value;
			}
		}
		
		private long generate;
		
		public synchronized long getGenerate() {
			synchronized(parent) {
				return generate;
			}
		}
		
		public void setGenerate(long value) {
			synchronized(parent) {
				this.generate = value;
			}
		}
		
	}
	
	public static class Sensor {
		private Environment parent;
		
		public Sensor(Environment parent) {
			this.parent = parent;
		}
		private boolean launchConnection;
		
		public synchronized boolean getLaunchConnection() {
			synchronized(parent) {
				return launchConnection;
			}
		}
		
		public void setLaunchConnection(boolean value) {
			synchronized(parent) {
				this.launchConnection = value;
			}
		}
		
		private boolean booleanOutput;
		
		public synchronized boolean getBooleanOutput() {
			synchronized(parent) {
				return booleanOutput;
			}
		}
		
		public void setBooleanOutput(boolean value) {
			synchronized(parent) {
				this.booleanOutput = value;
			}
		}
		
		private long numericalOutput;
		
		public synchronized long getNumericalOutput() {
			synchronized(parent) {
				return numericalOutput;
			}
		}
		
		public void setNumericalOutput(long value) {
			synchronized(parent) {
				this.numericalOutput = value;
			}
		}
		
	}
	
	public static class Generator {
		private Environment parent;
		
		public Generator(Environment parent) {
			this.parent = parent;
		}
		private long random_val;
		
		public synchronized long getRandom_val() {
			synchronized(parent) {
				return random_val;
			}
		}
		
		public void setRandom_val(long value) {
			synchronized(parent) {
				this.random_val = value;
			}
		}
		
	}
	
	protected Clock clock;
	
	protected Simulator simulator;
	
	protected Time time;
	
	protected Sensor sensor;
	
	protected Generator generator;
	
	public enum State {
		SIMENVIRONMENT_STOP_SIMULATION,
		SIMENVIRONMENT_START_SIMULATION,
		SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_INITIALIZE_SIMULATION,
		SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN,
		SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHGLOBALCLOCK,
		SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHSIMULATION,
		SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_EVALUATORTERMINATED,
		SIMENVIRONMENT_START_SIMULATION_CLOCK_STOP_CLOCK,
		SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK,
		SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK_RUNNING_RUNNING,
		SIMENVIRONMENT_START_SIMULATION_SENSORS_LAUNCHSENSORS,
		SIMENVIRONMENT_START_SIMULATION_SENSORS_SENDINGSIGNALTOSENSORS,
		SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR,
		SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_ONWAIT,
		SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING,
		SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_LAUNCH,
		SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_READING,
		SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING,
		SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_GENERATE_RANDOM_NUMBERS,
		SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_FEED_VALUES_,
		SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_TERMINATE,
		$NULLSTATE$
	};
	
	private State[] historyVector = new State[3];
	private final State[] stateVector = new State[4];
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[7];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		synchronized(Environment.this) {
			return isExecuting;
		}
	}
	
	protected void setIsExecuting(boolean value) {
		synchronized(Environment.this) {
			this.isExecuting = value;
		}
	}
	private long stateConfVectorPosition;
	
	protected long getStateConfVectorPosition() {
		synchronized(Environment.this) {
			return stateConfVectorPosition;
		}
	}
	
	protected void setStateConfVectorPosition(long value) {
		synchronized(Environment.this) {
			this.stateConfVectorPosition = value;
		}
	}
	public Environment() {
		clock = new Clock(this);
		simulator = new Simulator(this);
		time = new Time(this);
		sensor = new Sensor(this);
		generator = new Generator(this);
		for (int i = 0; i < 4; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		for (int i = 0; i < 3; i++) {
			historyVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		/* Default init sequence for statechart Environment */
		clock.setRunning(false);
		clock.setTimeRunning(0l);
		simulator.setRandomVal(0l);
		simulator.setProcessing(false);
		simulator.setReading(false);
		simulator.setGenerating(false);
		simulator.setTerminated(false);
		simulator.setBooleanOutput(false);
		simulator.setNumericalOutput(0l);
		time.setProcess(5l);
		time.setRead(5l);
		time.setGenerate(9999l);
		sensor.setLaunchConnection(false);
		sensor.setBooleanOutput(false);
		sensor.setNumericalOutput(0l);
		generator.setRandom_val(0l);
		
		isExecuting = false;
	}
	
	public synchronized void enter() {
		/* Activates the state machine. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		if (getIsExecuting()) {
			return
			;
		}
		isExecuting = true;
		/* Default enter sequence for statechart Environment */
		enterSequence_SimEnvironment_default();
		isExecuting = false;
	}
	
	public synchronized void exit() {
		/* Deactivates the state machine. */
		if (getIsExecuting()) {
			return
			;
		}
		isExecuting = true;
		/* Default exit sequence for statechart Environment */
		exitSequence_SimEnvironment();
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$||stateVector[1] != State.$NULLSTATE$||stateVector[2] != State.$NULLSTATE$||stateVector[3] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	private void clearInEvents() {
		run = false;
		start = false;
		stop = false;
		clock.run = false;
		clock.stop = false;
		clock.reset = false;
		simulator.launch = false;
		simulator.start = false;
		simulator.terminate = false;
		simulator.cycle = false;
		timeEvents[0] = false;
		timeEvents[1] = false;
		timeEvents[2] = false;
		timeEvents[3] = false;
		timeEvents[4] = false;
		timeEvents[5] = false;
		timeEvents[6] = false;
	}
	
	private void microStep() {
		long transitioned = -1l;
		stateConfVectorPosition = 0l;
		switch (stateVector[0]) {
		case SIMENVIRONMENT_STOP_SIMULATION:
			transitioned = simEnvironment_Stop_Simulation_react(transitioned);
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_INITIALIZE_SIMULATION:
			transitioned = simEnvironment_Start_Simulation_Initialization_Initialize_Simulation_react(transitioned);
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHGLOBALCLOCK:
			transitioned = simEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock_react(transitioned);
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHSIMULATION:
			transitioned = simEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation_react(transitioned);
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_EVALUATORTERMINATED:
			transitioned = simEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated_react(transitioned);
			break;
		default:
			break;
		}
		if (getStateConfVectorPosition()<1l) {
			switch (stateVector[1]) {
			case SIMENVIRONMENT_START_SIMULATION_CLOCK_STOP_CLOCK:
				transitioned = simEnvironment_Start_Simulation_Clock_Stop_Clock_react(transitioned);
				break;
			case SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK_RUNNING_RUNNING:
				transitioned = simEnvironment_Start_Simulation_Clock_Run_Clock_running_Running_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<2l) {
			switch (stateVector[2]) {
			case SIMENVIRONMENT_START_SIMULATION_SENSORS_LAUNCHSENSORS:
				transitioned = simEnvironment_Start_Simulation_Sensors_LaunchSensors_react(transitioned);
				break;
			case SIMENVIRONMENT_START_SIMULATION_SENSORS_SENDINGSIGNALTOSENSORS:
				transitioned = simEnvironment_Start_Simulation_Sensors_SendingSignalToSensors_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<3l) {
			switch (stateVector[3]) {
			case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_ONWAIT:
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_OnWait_react(transitioned);
				break;
			case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_LAUNCH:
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch_react(transitioned);
				break;
			case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_READING:
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading_react(transitioned);
				break;
			case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_GENERATE_RANDOM_NUMBERS:
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers_react(transitioned);
				break;
			case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_FEED_VALUES_:
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values__react(transitioned);
				break;
			case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_TERMINATE:
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_terminate_react(transitioned);
				break;
			default:
				break;
			}
		}
	}
	
	private void runCycle() {
		/* Performs a 'run to completion' step. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		if (getIsExecuting()) {
			return
			;
		}
		isExecuting = true;
		nextEvent();
		do { 
			microStep();
			clearInEvents();
		} while (nextEvent());
		isExecuting = false;
	}
	
	protected boolean nextEvent() {
		if(!inEventQueue.isEmpty()) {
			inEventQueue.poll().run();
			return true;
		}
		return false;
	}
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case SIMENVIRONMENT_STOP_SIMULATION:
			return stateVector[0] == State.SIMENVIRONMENT_STOP_SIMULATION;
		case SIMENVIRONMENT_START_SIMULATION:
			return stateVector[0].ordinal() >= State.
					SIMENVIRONMENT_START_SIMULATION.ordinal()&& stateVector[0].ordinal() <= State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_TERMINATE.ordinal();
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_INITIALIZE_SIMULATION:
			return stateVector[0] == State.SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_INITIALIZE_SIMULATION;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN:
			return stateVector[0].ordinal() >= State.
					SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN.ordinal()&& stateVector[0].ordinal() <= State.SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_EVALUATORTERMINATED.ordinal();
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHGLOBALCLOCK:
			return stateVector[0] == State.SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHGLOBALCLOCK;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHSIMULATION:
			return stateVector[0] == State.SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHSIMULATION;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_EVALUATORTERMINATED:
			return stateVector[0] == State.SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_EVALUATORTERMINATED;
		case SIMENVIRONMENT_START_SIMULATION_CLOCK_STOP_CLOCK:
			return stateVector[1] == State.SIMENVIRONMENT_START_SIMULATION_CLOCK_STOP_CLOCK;
		case SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK:
			return stateVector[1].ordinal() >= State.
					SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK.ordinal()&& stateVector[1].ordinal() <= State.SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK_RUNNING_RUNNING.ordinal();
		case SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK_RUNNING_RUNNING:
			return stateVector[1] == State.SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK_RUNNING_RUNNING;
		case SIMENVIRONMENT_START_SIMULATION_SENSORS_LAUNCHSENSORS:
			return stateVector[2] == State.SIMENVIRONMENT_START_SIMULATION_SENSORS_LAUNCHSENSORS;
		case SIMENVIRONMENT_START_SIMULATION_SENSORS_SENDINGSIGNALTOSENSORS:
			return stateVector[2] == State.SIMENVIRONMENT_START_SIMULATION_SENSORS_SENDINGSIGNALTOSENSORS;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR:
			return stateVector[3].ordinal() >= State.
					SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR.ordinal()&& stateVector[3].ordinal() <= State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_TERMINATE.ordinal();
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_ONWAIT:
			return stateVector[3] == State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_ONWAIT;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING:
			return stateVector[3].ordinal() >= State.
					SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING.ordinal()&& stateVector[3].ordinal() <= State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_TERMINATE.ordinal();
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_LAUNCH:
			return stateVector[3] == State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_LAUNCH;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_READING:
			return stateVector[3] == State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_READING;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING:
			return stateVector[3].ordinal() >= State.
					SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING.ordinal()&& stateVector[3].ordinal() <= State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_FEED_VALUES_.ordinal();
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_GENERATE_RANDOM_NUMBERS:
			return stateVector[3] == State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_GENERATE_RANDOM_NUMBERS;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_FEED_VALUES_:
			return stateVector[3] == State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_FEED_VALUES_;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_TERMINATE:
			return stateVector[3] == State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_TERMINATE;
		default:
			return false;
		}
	}
	
	public synchronized void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public synchronized void raiseTimeEvent(int eventID) {
		inEventQueue.add(() -> {
			timeEvents[eventID] = true;
		});
		runCycle();
	}
	
	public Clock clock() {
		return clock;
	}
	
	public Simulator simulator() {
		return simulator;
	}
	
	public Time time() {
		return time;
	}
	
	public Sensor sensor() {
		return sensor;
	}
	
	public Generator generator() {
		return generator;
	}
	
	
	private boolean run;
	
	
	public void raiseRun() {
		synchronized(Environment.this) {
			inEventQueue.add(() -> {
				run = true;
			});
			runCycle();
		}
	}
	
	private boolean start;
	
	
	public void raiseStart() {
		synchronized(Environment.this) {
			inEventQueue.add(() -> {
				start = true;
			});
			runCycle();
		}
	}
	
	private boolean stop;
	
	
	public void raiseStop() {
		synchronized(Environment.this) {
			inEventQueue.add(() -> {
				stop = true;
			});
			runCycle();
		}
	}
	
	private void effect_SimEnvironment_Start_Simulation_Clock_Run_Clock_tr1() {
		exitSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock();
		enterSequence_SimEnvironment_Start_Simulation_Clock_Stop_Clock_default();
	}
	
	/* Entry action for state 'LaunchGlobalClock'. */
	private void entryAction_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock() {
		/* Entry action for state 'LaunchGlobalClock'. */
		clock.raiseRun();
	}
	
	/* Entry action for state 'LaunchSimulation'. */
	private void entryAction_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation() {
		/* Entry action for state 'LaunchSimulation'. */
		simulator.raiseStart();
	}
	
	/* Entry action for state 'EvaluatorTerminated'. */
	private void entryAction_SimEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated() {
		/* Entry action for state 'EvaluatorTerminated'. */
		timerService.setTimer(this, 0, (5l * 1000l), false);
	}
	
	/* Entry action for state 'Stop_Clock'. */
	private void entryAction_SimEnvironment_Start_Simulation_Clock_Stop_Clock() {
		/* Entry action for state 'Stop_Clock'. */
		clock.setRunning(false);
	}
	
	/* Entry action for state 'Run_Clock'. */
	private void entryAction_SimEnvironment_Start_Simulation_Clock_Run_Clock() {
		/* Entry action for state 'Run_Clock'. */
		clock.setRunning(true);
		simulator.raiseLaunch();
	}
	
	/* Entry action for state 'Running'. */
	private void entryAction_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running() {
		/* Entry action for state 'Running'. */
		timerService.setTimer(this, 1, (1l * 1000l), true);
		clock.timeRunning++;
	}
	
	/* Entry action for state 'LaunchSensors'. */
	private void entryAction_SimEnvironment_Start_Simulation_Sensors_LaunchSensors() {
		/* Entry action for state 'LaunchSensors'. */
		if (clock.getRunning()) {
			sensor.setLaunchConnection(true);
		}
	}
	
	/* Entry action for state 'SendingSignalToSensors'. */
	private void entryAction_SimEnvironment_Start_Simulation_Sensors_SendingSignalToSensors() {
		/* Entry action for state 'SendingSignalToSensors'. */
		timerService.setTimer(this, 2, (1l * 1000l), false);
		sensor.setBooleanOutput(simulator.booleanOutput);
		sensor.setNumericalOutput(simulator.numericalOutput);
	}
	
	/* Entry action for state 'launch'. */
	private void entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch() {
		/* Entry action for state 'launch'. */
		timerService.setTimer(this, 3, (time.getProcess() * 1000l), false);
		simulator.setProcessing(true);
	}
	
	/* Entry action for state 'reading'. */
	private void entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading() {
		/* Entry action for state 'reading'. */
		timerService.setTimer(this, 4, (time.getRead() * 1000l), false);
		simulator.setReading(true);
	}
	
	/* Entry action for state 'monitoring'. */
	private void entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring() {
		/* Entry action for state 'monitoring'. */
		simulator.setGenerating(true);
	}
	
	/* Entry action for state 'generate_random_numbers'. */
	private void entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers() {
		/* Entry action for state 'generate_random_numbers'. */
		timerService.setTimer(this, 5, 500l, false);
	}
	
	/* Entry action for state 'feed_values '. */
	private void entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values_() {
		/* Entry action for state 'feed_values '. */
		timerService.setTimer(this, 6, 500l, false);
	}
	
	/* Entry action for state 'terminate'. */
	private void entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_terminate() {
		/* Entry action for state 'terminate'. */
		simulator.setTerminated(true);
		simulator.raiseTerminate();
	}
	
	/* Exit action for state 'EvaluatorTerminated'. */
	private void exitAction_SimEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated() {
		/* Exit action for state 'EvaluatorTerminated'. */
		timerService.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Running'. */
	private void exitAction_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running() {
		/* Exit action for state 'Running'. */
		timerService.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'SendingSignalToSensors'. */
	private void exitAction_SimEnvironment_Start_Simulation_Sensors_SendingSignalToSensors() {
		/* Exit action for state 'SendingSignalToSensors'. */
		timerService.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'launch'. */
	private void exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch() {
		/* Exit action for state 'launch'. */
		timerService.unsetTimer(this, 3);
		simulator.setProcessing(false);
	}
	
	/* Exit action for state 'reading'. */
	private void exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading() {
		/* Exit action for state 'reading'. */
		timerService.unsetTimer(this, 4);
		simulator.setReading(false);
	}
	
	/* Exit action for state 'monitoring'. */
	private void exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring() {
		/* Exit action for state 'monitoring'. */
		simulator.setGenerating(false);
	}
	
	/* Exit action for state 'generate_random_numbers'. */
	private void exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers() {
		/* Exit action for state 'generate_random_numbers'. */
		timerService.unsetTimer(this, 5);
	}
	
	/* Exit action for state 'feed_values '. */
	private void exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values_() {
		/* Exit action for state 'feed_values '. */
		timerService.unsetTimer(this, 6);
	}
	
	/* Exit action for state 'terminate'. */
	private void exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_terminate() {
		/* Exit action for state 'terminate'. */
		simulator.setTerminated(false);
	}
	
	/* 'default' enter sequence for state Stop_Simulation */
	private void enterSequence_SimEnvironment_Stop_Simulation_default() {
		/* 'default' enter sequence for state Stop_Simulation */
		stateVector[0] = State.SIMENVIRONMENT_STOP_SIMULATION;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state Start_Simulation */
	private void enterSequence_SimEnvironment_Start_Simulation_default() {
		/* 'default' enter sequence for state Start_Simulation */
		enterSequence_SimEnvironment_Start_Simulation_Initialization_default();
		enterSequence_SimEnvironment_Start_Simulation_Clock_default();
		enterSequence_SimEnvironment_Start_Simulation_Sensors_default();
		enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_default();
	}
	
	/* 'default' enter sequence for state Initialize_Simulation */
	private void enterSequence_SimEnvironment_Start_Simulation_Initialization_Initialize_Simulation_default() {
		/* 'default' enter sequence for state Initialize_Simulation */
		stateVector[0] = State.SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_INITIALIZE_SIMULATION;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state Run */
	private void enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_default() {
		/* 'default' enter sequence for state Run */
		enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_default();
	}
	
	/* 'default' enter sequence for state LaunchGlobalClock */
	private void enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock_default() {
		/* 'default' enter sequence for state LaunchGlobalClock */
		entryAction_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock();
		stateVector[0] = State.SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHGLOBALCLOCK;
		stateConfVectorPosition = 0;
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state LaunchSimulation */
	private void enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation_default() {
		/* 'default' enter sequence for state LaunchSimulation */
		entryAction_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation();
		stateVector[0] = State.SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHSIMULATION;
		stateConfVectorPosition = 0;
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state EvaluatorTerminated */
	private void enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated_default() {
		/* 'default' enter sequence for state EvaluatorTerminated */
		entryAction_SimEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated();
		stateVector[0] = State.SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_EVALUATORTERMINATED;
		stateConfVectorPosition = 0;
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Stop_Clock */
	private void enterSequence_SimEnvironment_Start_Simulation_Clock_Stop_Clock_default() {
		/* 'default' enter sequence for state Stop_Clock */
		entryAction_SimEnvironment_Start_Simulation_Clock_Stop_Clock();
		stateVector[1] = State.SIMENVIRONMENT_START_SIMULATION_CLOCK_STOP_CLOCK;
		stateConfVectorPosition = 1;
		historyVector[1] = stateVector[1];
	}
	
	/* 'default' enter sequence for state Run_Clock */
	private void enterSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_default() {
		/* 'default' enter sequence for state Run_Clock */
		entryAction_SimEnvironment_Start_Simulation_Clock_Run_Clock();
		enterSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_default();
		historyVector[1] = stateVector[1];
	}
	
	/* 'default' enter sequence for state Running */
	private void enterSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running_default() {
		/* 'default' enter sequence for state Running */
		entryAction_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running();
		stateVector[1] = State.SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK_RUNNING_RUNNING;
		stateConfVectorPosition = 1;
		historyVector[2] = stateVector[1];
	}
	
	/* 'default' enter sequence for state LaunchSensors */
	private void enterSequence_SimEnvironment_Start_Simulation_Sensors_LaunchSensors_default() {
		/* 'default' enter sequence for state LaunchSensors */
		entryAction_SimEnvironment_Start_Simulation_Sensors_LaunchSensors();
		stateVector[2] = State.SIMENVIRONMENT_START_SIMULATION_SENSORS_LAUNCHSENSORS;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state SendingSignalToSensors */
	private void enterSequence_SimEnvironment_Start_Simulation_Sensors_SendingSignalToSensors_default() {
		/* 'default' enter sequence for state SendingSignalToSensors */
		entryAction_SimEnvironment_Start_Simulation_Sensors_SendingSignalToSensors();
		stateVector[2] = State.SIMENVIRONMENT_START_SIMULATION_SENSORS_SENDINGSIGNALTOSENSORS;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state EnvironmentEvaluator */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_default() {
		/* 'default' enter sequence for state EnvironmentEvaluator */
		enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_default();
	}
	
	/* 'default' enter sequence for state OnWait */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_OnWait_default() {
		/* 'default' enter sequence for state OnWait */
		stateVector[3] = State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_ONWAIT;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state Simulating */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_default() {
		/* 'default' enter sequence for state Simulating */
		enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_default();
	}
	
	/* 'default' enter sequence for state launch */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch_default() {
		/* 'default' enter sequence for state launch */
		entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch();
		stateVector[3] = State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_LAUNCH;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state reading */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading_default() {
		/* 'default' enter sequence for state reading */
		entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading();
		stateVector[3] = State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_READING;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state monitoring */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_default() {
		/* 'default' enter sequence for state monitoring */
		entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring();
		enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_default();
	}
	
	/* 'default' enter sequence for state generate_random_numbers */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers_default() {
		/* 'default' enter sequence for state generate_random_numbers */
		entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers();
		stateVector[3] = State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_GENERATE_RANDOM_NUMBERS;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state feed_values  */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values__default() {
		/* 'default' enter sequence for state feed_values  */
		entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values_();
		stateVector[3] = State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_FEED_VALUES_;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state terminate */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_terminate_default() {
		/* 'default' enter sequence for state terminate */
		entryAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_terminate();
		stateVector[3] = State.SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_TERMINATE;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for region SimEnvironment */
	private void enterSequence_SimEnvironment_default() {
		/* 'default' enter sequence for region SimEnvironment */
		react_SimEnvironment__entry_Default();
	}
	
	/* 'default' enter sequence for region Initialization */
	private void enterSequence_SimEnvironment_Start_Simulation_Initialization_default() {
		/* 'default' enter sequence for region Initialization */
		react_SimEnvironment_Start_Simulation_Initialization__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_default() {
		/* 'default' enter sequence for region r1 */
		react_SimEnvironment_Start_Simulation_Initialization_Run_r1__entry_Default();
	}
	
	/* shallow enterSequence with history in child r1 */
	private void shallowEnterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1() {
		/* shallow enterSequence with history in child r1 */
		switch (historyVector[0]) {
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHGLOBALCLOCK:
			enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock_default();
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHSIMULATION:
			enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation_default();
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_EVALUATORTERMINATED:
			enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated_default();
			break;
		default:
			break;
		}
	}
	
	/* 'default' enter sequence for region Clock */
	private void enterSequence_SimEnvironment_Start_Simulation_Clock_default() {
		/* 'default' enter sequence for region Clock */
		react_SimEnvironment_Start_Simulation_Clock__entry_Default();
	}
	
	/* deep enterSequence with history in child Clock */
	private void deepEnterSequence_SimEnvironment_Start_Simulation_Clock() {
		/* deep enterSequence with history in child Clock */
		switch (historyVector[1]) {
		case SIMENVIRONMENT_START_SIMULATION_CLOCK_STOP_CLOCK:
			/* enterSequence with history in child Stop_Clock for leaf Stop_Clock */
			enterSequence_SimEnvironment_Start_Simulation_Clock_Stop_Clock_default();
			break;
		case SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK_RUNNING_RUNNING:
			/* enterSequence with history in child Run_Clock for leaf Running */
			entryAction_SimEnvironment_Start_Simulation_Clock_Run_Clock();
			deepEnterSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running();
			break;
		default:
			break;
		}
	}
	
	/* 'default' enter sequence for region running */
	private void enterSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_default() {
		/* 'default' enter sequence for region running */
		react_SimEnvironment_Start_Simulation_Clock_Run_Clock_running__entry_Default();
	}
	
	/* deep enterSequence with history in child running */
	private void deepEnterSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running() {
		/* deep enterSequence with history in child running */
		switch (historyVector[2]) {
		case SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK_RUNNING_RUNNING:
			/* enterSequence with history in child Running for leaf Running */
			enterSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running_default();
			break;
		default:
			break;
		}
	}
	
	/* 'default' enter sequence for region Sensors */
	private void enterSequence_SimEnvironment_Start_Simulation_Sensors_default() {
		/* 'default' enter sequence for region Sensors */
		react_SimEnvironment_Start_Simulation_Sensors__entry_Default();
	}
	
	/* 'default' enter sequence for region SmartFire_Evaluator */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_default() {
		/* 'default' enter sequence for region SmartFire_Evaluator */
		react_SimEnvironment_Start_Simulation_SmartFire_Evaluator__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_default() {
		/* 'default' enter sequence for region r1 */
		react_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region F */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_default() {
		/* 'default' enter sequence for region F */
		react_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_default() {
		/* 'default' enter sequence for region r1 */
		react_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1__entry_Default();
	}
	
	/* Default exit sequence for state Stop_Simulation */
	private void exitSequence_SimEnvironment_Stop_Simulation() {
		/* Default exit sequence for state Stop_Simulation */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state Start_Simulation */
	private void exitSequence_SimEnvironment_Start_Simulation() {
		/* Default exit sequence for state Start_Simulation */
		exitSequence_SimEnvironment_Start_Simulation_Initialization();
		exitSequence_SimEnvironment_Start_Simulation_Clock();
		exitSequence_SimEnvironment_Start_Simulation_Sensors();
		exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator();
	}
	
	/* Default exit sequence for state Initialize_Simulation */
	private void exitSequence_SimEnvironment_Start_Simulation_Initialization_Initialize_Simulation() {
		/* Default exit sequence for state Initialize_Simulation */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state LaunchGlobalClock */
	private void exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock() {
		/* Default exit sequence for state LaunchGlobalClock */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state LaunchSimulation */
	private void exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation() {
		/* Default exit sequence for state LaunchSimulation */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state EvaluatorTerminated */
	private void exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated() {
		/* Default exit sequence for state EvaluatorTerminated */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
		exitAction_SimEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated();
	}
	
	/* Default exit sequence for state Stop_Clock */
	private void exitSequence_SimEnvironment_Start_Simulation_Clock_Stop_Clock() {
		/* Default exit sequence for state Stop_Clock */
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
	}
	
	/* Default exit sequence for state Run_Clock */
	private void exitSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock() {
		/* Default exit sequence for state Run_Clock */
		exitSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running();
	}
	
	/* Default exit sequence for state Running */
	private void exitSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running() {
		/* Default exit sequence for state Running */
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
		exitAction_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running();
	}
	
	/* Default exit sequence for state LaunchSensors */
	private void exitSequence_SimEnvironment_Start_Simulation_Sensors_LaunchSensors() {
		/* Default exit sequence for state LaunchSensors */
		stateVector[2] = State.$NULLSTATE$;
		stateConfVectorPosition = 2;
	}
	
	/* Default exit sequence for state SendingSignalToSensors */
	private void exitSequence_SimEnvironment_Start_Simulation_Sensors_SendingSignalToSensors() {
		/* Default exit sequence for state SendingSignalToSensors */
		stateVector[2] = State.$NULLSTATE$;
		stateConfVectorPosition = 2;
		exitAction_SimEnvironment_Start_Simulation_Sensors_SendingSignalToSensors();
	}
	
	/* Default exit sequence for state OnWait */
	private void exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_OnWait() {
		/* Default exit sequence for state OnWait */
		stateVector[3] = State.$NULLSTATE$;
		stateConfVectorPosition = 3;
	}
	
	/* Default exit sequence for state launch */
	private void exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch() {
		/* Default exit sequence for state launch */
		stateVector[3] = State.$NULLSTATE$;
		stateConfVectorPosition = 3;
		exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch();
	}
	
	/* Default exit sequence for state reading */
	private void exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading() {
		/* Default exit sequence for state reading */
		stateVector[3] = State.$NULLSTATE$;
		stateConfVectorPosition = 3;
		exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading();
	}
	
	/* Default exit sequence for state monitoring */
	private void exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring() {
		/* Default exit sequence for state monitoring */
		exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1();
		exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring();
	}
	
	/* Default exit sequence for state generate_random_numbers */
	private void exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers() {
		/* Default exit sequence for state generate_random_numbers */
		stateVector[3] = State.$NULLSTATE$;
		stateConfVectorPosition = 3;
		exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers();
	}
	
	/* Default exit sequence for state feed_values  */
	private void exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values_() {
		/* Default exit sequence for state feed_values  */
		stateVector[3] = State.$NULLSTATE$;
		stateConfVectorPosition = 3;
		exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values_();
	}
	
	/* Default exit sequence for state terminate */
	private void exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_terminate() {
		/* Default exit sequence for state terminate */
		stateVector[3] = State.$NULLSTATE$;
		stateConfVectorPosition = 3;
		exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_terminate();
	}
	
	/* Default exit sequence for region SimEnvironment */
	private void exitSequence_SimEnvironment() {
		/* Default exit sequence for region SimEnvironment */
		switch (stateVector[0]) {
		case SIMENVIRONMENT_STOP_SIMULATION:
			exitSequence_SimEnvironment_Stop_Simulation();
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_INITIALIZE_SIMULATION:
			exitSequence_SimEnvironment_Start_Simulation_Initialization_Initialize_Simulation();
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHGLOBALCLOCK:
			exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock();
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHSIMULATION:
			exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation();
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_EVALUATORTERMINATED:
			exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated();
			break;
		default:
			break;
		}
		switch (stateVector[1]) {
		case SIMENVIRONMENT_START_SIMULATION_CLOCK_STOP_CLOCK:
			exitSequence_SimEnvironment_Start_Simulation_Clock_Stop_Clock();
			break;
		case SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK_RUNNING_RUNNING:
			exitSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running();
			break;
		default:
			break;
		}
		switch (stateVector[2]) {
		case SIMENVIRONMENT_START_SIMULATION_SENSORS_LAUNCHSENSORS:
			exitSequence_SimEnvironment_Start_Simulation_Sensors_LaunchSensors();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SENSORS_SENDINGSIGNALTOSENSORS:
			exitSequence_SimEnvironment_Start_Simulation_Sensors_SendingSignalToSensors();
			break;
		default:
			break;
		}
		switch (stateVector[3]) {
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_ONWAIT:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_OnWait();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_LAUNCH:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_READING:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_GENERATE_RANDOM_NUMBERS:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers();
			exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_FEED_VALUES_:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values_();
			exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_TERMINATE:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_terminate();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Initialization */
	private void exitSequence_SimEnvironment_Start_Simulation_Initialization() {
		/* Default exit sequence for region Initialization */
		switch (stateVector[0]) {
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_INITIALIZE_SIMULATION:
			exitSequence_SimEnvironment_Start_Simulation_Initialization_Initialize_Simulation();
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHGLOBALCLOCK:
			exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock();
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_LAUNCHSIMULATION:
			exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation();
			break;
		case SIMENVIRONMENT_START_SIMULATION_INITIALIZATION_RUN_R1_EVALUATORTERMINATED:
			exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Clock */
	private void exitSequence_SimEnvironment_Start_Simulation_Clock() {
		/* Default exit sequence for region Clock */
		switch (stateVector[1]) {
		case SIMENVIRONMENT_START_SIMULATION_CLOCK_STOP_CLOCK:
			exitSequence_SimEnvironment_Start_Simulation_Clock_Stop_Clock();
			break;
		case SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK_RUNNING_RUNNING:
			exitSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region running */
	private void exitSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running() {
		/* Default exit sequence for region running */
		switch (stateVector[1]) {
		case SIMENVIRONMENT_START_SIMULATION_CLOCK_RUN_CLOCK_RUNNING_RUNNING:
			exitSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Sensors */
	private void exitSequence_SimEnvironment_Start_Simulation_Sensors() {
		/* Default exit sequence for region Sensors */
		switch (stateVector[2]) {
		case SIMENVIRONMENT_START_SIMULATION_SENSORS_LAUNCHSENSORS:
			exitSequence_SimEnvironment_Start_Simulation_Sensors_LaunchSensors();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SENSORS_SENDINGSIGNALTOSENSORS:
			exitSequence_SimEnvironment_Start_Simulation_Sensors_SendingSignalToSensors();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region SmartFire_Evaluator */
	private void exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator() {
		/* Default exit sequence for region SmartFire_Evaluator */
		switch (stateVector[3]) {
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_ONWAIT:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_OnWait();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_LAUNCH:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_READING:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_GENERATE_RANDOM_NUMBERS:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers();
			exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_FEED_VALUES_:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values_();
			exitAction_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_TERMINATE:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_terminate();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1() {
		/* Default exit sequence for region r1 */
		switch (stateVector[3]) {
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_GENERATE_RANDOM_NUMBERS:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers();
			break;
		case SIMENVIRONMENT_START_SIMULATION_SMARTFIRE_EVALUATOR_ENVIRONMENTEVALUATOR_R1_SIMULATING_F_MONITORING_R1_FEED_VALUES_:
			exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values_();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_SimEnvironment__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SimEnvironment_Stop_Simulation_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SimEnvironment_Start_Simulation_Initialization__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SimEnvironment_Start_Simulation_Initialization_Initialize_Simulation_default();
	}
	
	/* Default react sequence for shallow history entry  */
	private void react_SimEnvironment_Start_Simulation_Initialization_Run_r1__entry_Default() {
		/* Default react sequence for shallow history entry  */
		/* Enter the region with shallow history */
		if (historyVector[0] != State.$NULLSTATE$) {
			shallowEnterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1();
		} else {
			enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock_default();
		}
	}
	
	/* Default react sequence for deep history entry  */
	private void react_SimEnvironment_Start_Simulation_Clock__entry_Default() {
		/* Default react sequence for deep history entry  */
		/* Enter the region with deep history */
		if (historyVector[1] != State.$NULLSTATE$) {
			deepEnterSequence_SimEnvironment_Start_Simulation_Clock();
		} else {
			enterSequence_SimEnvironment_Start_Simulation_Clock_Stop_Clock_default();
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_SimEnvironment_Start_Simulation_Clock_Run_Clock_running__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SimEnvironment_Start_Simulation_Sensors__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SimEnvironment_Start_Simulation_Sensors_LaunchSensors_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SimEnvironment_Start_Simulation_SmartFire_Evaluator__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_OnWait_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers_default();
	}
	
	/* The reactions of exit default. */
	private void react_SimEnvironment_Start_Simulation_Clock_Run_Clock_running__exit_Default() {
		/* The reactions of exit default. */
		effect_SimEnvironment_Start_Simulation_Clock_Run_Clock_tr1();
	}
	
	private long react(long transitioned_before) {
		/* State machine reactions. */
		return transitioned_before
		;
	}
	
	private long simEnvironment_Stop_Simulation_react(long transitioned_before) {
		/* The reactions of state Stop_Simulation. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (start) {
				exitSequence_SimEnvironment_Stop_Simulation();
				enterSequence_SimEnvironment_Start_Simulation_default();
				react(0l);
				transitioned_after = 0l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_react(long transitioned_before) {
		/* The reactions of state Start_Simulation. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (stop) {
				exitSequence_SimEnvironment_Start_Simulation();
				enterSequence_SimEnvironment_Stop_Simulation_default();
				react(0l);
				transitioned_after = 3l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_Initialization_Initialize_Simulation_react(long transitioned_before) {
		/* The reactions of state Initialize_Simulation. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (run) {
				exitSequence_SimEnvironment_Start_Simulation_Initialization_Initialize_Simulation();
				enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_Initialization_Run_react(long transitioned_before) {
		/* The reactions of state Run. */
		return transitioned_before
		;
	}
	
	private long simEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock_react(long transitioned_before) {
		/* The reactions of state LaunchGlobalClock. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (clock.reset) {
				exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock();
				clock.raiseStop();
				enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock_default();
				simEnvironment_Start_Simulation_Initialization_Run_react(0l);
				transitioned_after = 0l;
			} else {
				if (simulator.launch) {
					exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchGlobalClock();
					enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation_default();
					simEnvironment_Start_Simulation_Initialization_Run_react(0l);
					transitioned_after = 0l;
				}
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = simEnvironment_Start_Simulation_Initialization_Run_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation_react(long transitioned_before) {
		/* The reactions of state LaunchSimulation. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (simulator.terminate) {
				exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation();
				enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated_default();
				simEnvironment_Start_Simulation_Initialization_Run_react(0l);
				transitioned_after = 0l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = simEnvironment_Start_Simulation_Initialization_Run_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated_react(long transitioned_before) {
		/* The reactions of state EvaluatorTerminated. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (simulator.cycle) {
				exitSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_EvaluatorTerminated();
				enterSequence_SimEnvironment_Start_Simulation_Initialization_Run_r1_LaunchSimulation_default();
				simEnvironment_Start_Simulation_Initialization_Run_react(0l);
				transitioned_after = 0l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			if (timeEvents[0]) {
				simulator.raiseCycle();
			}
			transitioned_after = simEnvironment_Start_Simulation_Initialization_Run_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_Clock_Stop_Clock_react(long transitioned_before) {
		/* The reactions of state Stop_Clock. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (clock.run) {
				exitSequence_SimEnvironment_Start_Simulation_Clock_Stop_Clock();
				enterSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_default();
				transitioned_after = 1l;
			}
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_Clock_Run_Clock_react(long transitioned_before) {
		/* The reactions of state Run_Clock. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (clock.stop) {
				exitSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock();
				enterSequence_SimEnvironment_Start_Simulation_Clock_Stop_Clock_default();
				transitioned_after = 1l;
			}
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_Clock_Run_Clock_running_Running_react(long transitioned_before) {
		/* The reactions of state Running. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (timeEvents[1]) {
				exitSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running();
				timeEvents[1] = false;
				enterSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running_default();
				simEnvironment_Start_Simulation_Clock_Run_Clock_react(1l);
				transitioned_after = 1l;
			} else {
				if (clock.stop) {
					exitSequence_SimEnvironment_Start_Simulation_Clock_Run_Clock_running_Running();
					react_SimEnvironment_Start_Simulation_Clock_Run_Clock_running__exit_Default();
					transitioned_after = 1l;
				}
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = simEnvironment_Start_Simulation_Clock_Run_Clock_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_Sensors_LaunchSensors_react(long transitioned_before) {
		/* The reactions of state LaunchSensors. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (simulator.start) {
				exitSequence_SimEnvironment_Start_Simulation_Sensors_LaunchSensors();
				enterSequence_SimEnvironment_Start_Simulation_Sensors_SendingSignalToSensors_default();
				transitioned_after = 2l;
			}
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_Sensors_SendingSignalToSensors_react(long transitioned_before) {
		/* The reactions of state SendingSignalToSensors. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<2l) {
			if (timeEvents[2]) {
				exitSequence_SimEnvironment_Start_Simulation_Sensors_SendingSignalToSensors();
				timeEvents[2] = false;
				enterSequence_SimEnvironment_Start_Simulation_Sensors_SendingSignalToSensors_default();
				transitioned_after = 2l;
			}
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_react(long transitioned_before) {
		/* The reactions of state EnvironmentEvaluator. */
		long transitioned_after = transitioned_before;
		/* If no transition was taken then execute local reactions */
		transitioned_after = simEnvironment_Start_Simulation_react(transitioned_before);
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_OnWait_react(long transitioned_before) {
		/* The reactions of state OnWait. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (simulator.start) {
				exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_OnWait();
				enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_default();
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_react(3l);
				transitioned_after = 3l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_react(long transitioned_before) {
		/* The reactions of state Simulating. */
		long transitioned_after = transitioned_before;
		/* If no transition was taken then execute local reactions */
		transitioned_after = simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_react(transitioned_before);
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch_react(long transitioned_before) {
		/* The reactions of state launch. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (timeEvents[3]) {
				exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_launch();
				timeEvents[3] = false;
				enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading_default();
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_react(3l);
				transitioned_after = 3l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading_react(long transitioned_before) {
		/* The reactions of state reading. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (timeEvents[4]) {
				exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_reading();
				timeEvents[4] = false;
				enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_default();
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_react(3l);
				transitioned_after = 3l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_react(long transitioned_before) {
		/* The reactions of state monitoring. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (simulator.terminate) {
				exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring();
				enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_terminate_default();
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_react(3l);
				transitioned_after = 3l;
			} else {
				if (simulator.cycle) {
					exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring();
					enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_default();
					simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_react(3l);
					transitioned_after = 3l;
				}
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers_react(long transitioned_before) {
		/* The reactions of state generate_random_numbers. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (timeEvents[5]) {
				exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers();
				timeEvents[5] = false;
				enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values__default();
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_react(3l);
				transitioned_after = 3l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values__react(long transitioned_before) {
		/* The reactions of state feed_values . */
		long transitioned_after = transitioned_before;
		if (transitioned_after<3l) {
			if (timeEvents[6]) {
				exitSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_feed_values_();
				timeEvents[6] = false;
				enterSequence_SimEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_r1_generate_random_numbers_default();
				simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_react(3l);
				transitioned_after = 3l;
			}
		}
		if (transitioned_after==transitioned_before) {
			/* If no transition was taken then execute local reactions */
			transitioned_after = simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_monitoring_react(transitioned_before);
		}
		return transitioned_after
		;
	}
	
	private long simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_F_terminate_react(long transitioned_before) {
		/* The reactions of state terminate. */
		long transitioned_after = transitioned_before;
		/* If no transition was taken then execute local reactions */
		transitioned_after = simEnvironment_Start_Simulation_SmartFire_Evaluator_EnvironmentEvaluator_r1_Simulating_react(transitioned_before);
		return transitioned_after
		;
	}
	
	/* Can be used by the client code to trigger a run to completion step without raising an event. */
	public synchronized void triggerWithoutEvent() {
		runCycle();
	}
}
