/** Generated by itemis CREATE code generator. */

#ifndef HUB_POWERMANAGER_META_H_
#define HUB_POWERMANAGER_META_H_

#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern sc_string Hub_PowerManager_meta_feature_names[];

extern sc_string Hub_PowerManager_meta_state_names[];

#ifdef __cplusplus
}
#endif

#endif /* HUB_POWERMANAGER_META_H_ */
