/** Generated by itemis CREATE code generator. */

#include "SmartTVSystem_meta.h"
		
sc_string SmartTVSystem_meta_feature_names[] = {
	"<nothing>",
	"Actuator",
	"Controller",
	"Sensor",
	"WiFi",
	"Power",
	"Temp",
	"TV",
	"message",
	"WiFi_connection",
	"Temp_value",
	"Power_input",
	"Power_total",
	"Power_required",
	"system.on",
	"system.off",
	"system.connect_network",
	"system.disconnect_network",
	"system.isOn",
	"SensorInput.detection_time",
	"SensorInput.timeout_time",
	"SensorOutput.counter",
	"SensorOutput.activity"
};

sc_string SmartTVSystem_meta_state_names[] = {
	"<nostate>",
	"_SmartTVSystem_.SmartTVSystem",
	"_SmartTVSystem_.SmartTVSystem.SystemStatus.off",
	"_SmartTVSystem_.SmartTVSystem.SystemStatus.on",
	"_SmartTVSystem_.SmartTVSystem.ActuatorComponent._Actuator_Updates_",
	"_SmartTVSystem_.SmartTVSystem.ActuatorComponent._Device_Functioning_",
	"_SmartTVSystem_.SmartTVSystem.ActuatorComponent.off",
	"_SmartTVSystem_.SmartTVSystem.ControllerComponent._Initialize_Controller_Component_",
	"_SmartTVSystem_.SmartTVSystem.ControllerComponent._Initialize_Controller_Component_.updating._Controller_Updates_",
	"_SmartTVSystem_.SmartTVSystem.ControllerComponent.off",
	"_SmartTVSystem_.SmartTVSystem.SensorComponent._Initialize_Sensor_Component_",
	"_SmartTVSystem_.SmartTVSystem.SensorComponent._Initialize_Sensor_Component_.updating._Sensor_Updates_",
	"_SmartTVSystem_.SmartTVSystem.SensorComponent.off",
	"_SmartTVSystem_.SmartTVSystem.NetworkComponent._Initialize_WiFi_Component_",
	"_SmartTVSystem_.SmartTVSystem.NetworkComponent._Initialize_WiFi_Component_.updating._WiFi_Updates_",
	"_SmartTVSystem_.SmartTVSystem.NetworkComponent.off",
	"_SmartTVSystem_.SmartTVSystem.PowerCalculatorComponent._Initialize_Power_Component_",
	"_SmartTVSystem_.SmartTVSystem.PowerCalculatorComponent._Initialize_Power_Component_.updating._Power_Updates_",
	"_SmartTVSystem_.SmartTVSystem.PowerCalculatorComponent.off",
	"_SmartTVSystem_.SmartTVSystem.trackingDeviceTemperature._Initialize_DeviceTemp_Component_",
	"_SmartTVSystem_.SmartTVSystem.trackingDeviceTemperature._Initialize_DeviceTemp_Component_.updating._Temperature_Updates_",
	"_SmartTVSystem_.SmartTVSystem.trackingDeviceTemperature.off"
};
