/** Generated by itemis CREATE code generator. */


#ifndef SMARTTVSYSTEM1TRACER_H_
#define SMARTTVSYSTEM1TRACER_H_


#include "../src/yet_sc_tracer.h"


#include "SmartTVSystem1.h"
#include "SmartTVSystem1_meta.h"


#ifdef __cplusplus
extern "C"
{
#endif


extern void smartTVSystem1_init_sc_tracer(yet_sc_tracer *tracer, SmartTVSystem1* machine, sc_string name);


#ifdef __cplusplus
}
#endif


#endif /* SMARTTVSYSTEM1TRACER_H_ */
