/** Generated by itemis CREATE code generator. */


#ifndef SMARTFIRESYSTEMTRACER_H_
#define SMARTFIRESYSTEMTRACER_H_


#include "../src/yet_sc_tracer.h"


#include "SmartFireSystem.h"
#include "SmartFireSystem_meta.h"


#ifdef __cplusplus
extern "C"
{
#endif


extern void smartFireSystem_init_sc_tracer(yet_sc_tracer *tracer, SmartFireSystem* machine, sc_string name);


#ifdef __cplusplus
}
#endif


#endif /* SMARTFIRESYSTEMTRACER_H_ */
