/** Generated by itemis CREATE code generator. */


#ifndef TV_UNITTRACER_H_
#define TV_UNITTRACER_H_


#include "../src/yet_sc_tracer.h"


#include "TV_Unit.h"
#include "TV_Unit_meta.h"


#ifdef __cplusplus
extern "C"
{
#endif


extern void tV_Unit_init_sc_tracer(yet_sc_tracer *tracer, TV_Unit* machine, sc_string name);


#ifdef __cplusplus
}
#endif


#endif /* TV_UNITTRACER_H_ */
