/** Generated by itemis CREATE code generator. */


#ifndef ELEVATOR_UNITTRACER_H_
#define ELEVATOR_UNITTRACER_H_


#include "../src/yet_sc_tracer.h"


#include "Elevator_Unit.h"
#include "Elevator_Unit_meta.h"


#ifdef __cplusplus
extern "C"
{
#endif


extern void elevator_Unit_init_sc_tracer(yet_sc_tracer *tracer, Elevator_Unit* machine, sc_string name);


#ifdef __cplusplus
}
#endif


#endif /* ELEVATOR_UNITTRACER_H_ */
