/** Generated by itemis CREATE code generator. */

#ifndef FIREALARM_UNIT_META_H_
#define FIREALARM_UNIT_META_H_

#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern sc_string FireAlarm_Unit_meta_feature_names[];

extern sc_string FireAlarm_Unit_meta_state_names[];

#ifdef __cplusplus
}
#endif

#endif /* FIREALARM_UNIT_META_H_ */
