/** Generated by itemis CREATE code generator. */

#include "Hub_PowerManager_meta.h"
		
sc_string Hub_PowerManager_meta_feature_names[] = {
	"<nothing>",
	"threshold_reached",
	"total",
	"threshold",
	"prev_last_value",
	"last_value",
	"previous_device_index",
	"device_index",
	"system_index_to_turnoff",
	"over_threshold"
};

sc_string Hub_PowerManager_meta_state_names[] = {
	"<nostate>",
	"_HUB_PowerManager_.monitoring_power_consumption",
	"_HUB_PowerManager_.threshold_reached",
	"_HUB_PowerManager_.threshold_reached._Return_DeviceIndex_To_Be_TurnedOFF_.initialize_last_value",
	"_HUB_PowerManager_.double_check"
};
