/** Generated by itemis CREATE code generator. */

#include "HubTemplate_meta.h"
		
sc_string HubTemplate_meta_feature_names[] = {
	"<nothing>",
	"PowerManager",
	"toggle",
	"HubON",
	"HubOFF",
	"totalSystemsON",
	"HUB.TurnONSystems",
	"HUB.TurnOFFSystems",
	"HUB.AllSystemsOFF",
	"HUB.AllSystemsON",
	"Power.index",
	"Power.total",
	"Power.threshold",
	"Power.thresholdReached",
	"System1.toggle",
	"System1.isON",
	"System1.isOFF",
	"System2.toggle",
	"System2.isON",
	"System2.isOFF"
};

sc_string HubTemplate_meta_state_names[] = {
	"<nostate>",
	"_HUB_Template_.HubOff",
	"_HUB_Template_.HUBTemplate",
	"_HUB_Template_.HUBTemplate.SmartHubRegion.SmartHubSystemStatus",
	"_HUB_Template_.HUBTemplate.SmartHubRegion.SmartHubSystemStatus.HubStatusRegion.AllSystemsOFF",
	"_HUB_Template_.HUBTemplate.SmartHubRegion.SmartHubSystemStatus.HubStatusRegion.System_Manager",
	"_HUB_Template_.HUBTemplate.SmartHubRegion.SmartHubSystemStatus.HubStatusRegion.System_Manager.System1.System1ON",
	"_HUB_Template_.HUBTemplate.SmartHubRegion.SmartHubSystemStatus.HubStatusRegion.System_Manager.System1.System1OFF",
	"_HUB_Template_.HUBTemplate.SmartHubRegion.SmartHubSystemStatus.HubStatusRegion.System_Manager.System2.System2ON",
	"_HUB_Template_.HUBTemplate.SmartHubRegion.SmartHubSystemStatus.HubStatusRegion.System_Manager.System2.System2OFF",
	"_HUB_Template_.HUBTemplate.PowerConsumptionRegion.PowerConsumptionCalculator",
	"_HUB_Template_.HUBTemplate.PowerConsumptionRegion.IOT_EnergySaverManager",
	"_HUB_Template_.HUBTemplate.PowerConsumptionRegion.IOT_EnergySaverManager.turningoff_device_overthreshold.System1",
	"_HUB_Template_.HUBTemplate.PowerConsumptionRegion.IOT_EnergySaverManager.turningoff_device_overthreshold.System2",
	"_HUB_Template_.HUBTemplate.PowerConsumptionRegion.IOT_EnergySaverManager.turningoff_device_overthreshold._final_",
	"_HUB_Template_.HUBTemplate.System1Region.System1_status",
	"_HUB_Template_.HUBTemplate.System2Region.System2_status"
};
