/** Generated by itemis CREATE code generator. */


#ifndef HUBTEMPLATETRACER_H_
#define HUBTEMPLATETRACER_H_


#include "../src/yet_sc_tracer.h"


#include "HubTemplate.h"
#include "HubTemplate_meta.h"


#ifdef __cplusplus
extern "C"
{
#endif


extern void hubTemplate_init_sc_tracer(yet_sc_tracer *tracer, HubTemplate* machine, sc_string name);


#ifdef __cplusplus
}
#endif


#endif /* HUBTEMPLATETRACER_H_ */
