/** Generated by itemis CREATE code generator. */

#include "Network_Component_meta.h"
		
sc_string Network_Component_meta_feature_names[] = {
	"<nothing>",
	"on",
	"off",
	"timeout_counter",
	"timeout_value",
	"reconnect_value",
	"connection"
};

sc_string Network_Component_meta_state_names[] = {
	"<nostate>",
	"_Network_Component_._Network_Component_Working_",
	"_Network_Component_._Network_Component_Working_._Network_Connection_.checkingForNetworkConnection",
	"_Network_Component_._Network_Component_Working_._Network_Connection_.checkingForNetworkConnection._CheckingForConnectionUpdates_.connectingToServer",
	"_Network_Component_._Network_Component_Working_._Network_Connection_.checkingForNetworkConnection._CheckingForConnectionUpdates_.connectingToServer._Server_Connection_.success",
	"_Network_Component_._Network_Component_Working_._Network_Connection_.checkingForNetworkConnection._CheckingForConnectionUpdates_.connectingToServer._Server_Connection_.failure",
	"_Network_Component_._Network_Component_Working_._Network_Connection_.networkTimeout",
	"_Network_Component_._off_"
};
