/** Generated by itemis CREATE code generator. */


#ifndef SMARTTRAFFICLIGHTSYSTEMTRACER_H_
#define SMARTTRAFFICLIGHTSYSTEMTRACER_H_


#include "../src/yet_sc_tracer.h"


#include "SmartTrafficLightSystem.h"
#include "SmartTrafficLightSystem_meta.h"


#ifdef __cplusplus
extern "C"
{
#endif


extern void smartTrafficLightSystem_init_sc_tracer(yet_sc_tracer *tracer, SmartTrafficLightSystem* machine, sc_string name);


#ifdef __cplusplus
}
#endif


#endif /* SMARTTRAFFICLIGHTSYSTEMTRACER_H_ */
