/** Generated by itemis CREATE code generator. */

#ifndef SMARTHUBSYSTEM_META_H_
#define SMARTHUBSYSTEM_META_H_

#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern sc_string SmartHubSystem_meta_feature_names[];

extern sc_string SmartHubSystem_meta_state_names[];

#ifdef __cplusplus
}
#endif

#endif /* SMARTHUBSYSTEM_META_H_ */
