/** Generated by itemis CREATE code generator. */

#include "SmartTrafficLightSystem_meta.h"
		
sc_string SmartTrafficLightSystem_meta_feature_names[] = {
	"<nothing>",
	"Actuator",
	"Controller",
	"Sensor",
	"WiFi",
	"Power",
	"Temp",
	"TrafficLight",
	"message",
	"WiFi_connection",
	"Temp_value",
	"Power_input",
	"Power_total",
	"Power_required",
	"system.on",
	"system.off",
	"system.isOn",
	"system.light_status",
	"system.crossing_status",
	"system.timer",
	"SensorInput.detection_time",
	"SensorInput.timeout_time",
	"SensorOutput.counter",
	"SensorOutput.activity"
};

sc_string SmartTrafficLightSystem_meta_state_names[] = {
	"<nostate>",
	"main_region.SmartTrafficLightSystem",
	"main_region.SmartTrafficLightSystem.SystemStatus.off",
	"main_region.SmartTrafficLightSystem.SystemStatus.on",
	"main_region.SmartTrafficLightSystem.ActuatorComponent._Actuator_Updates_",
	"main_region.SmartTrafficLightSystem.ActuatorComponent._Device_Functioning_",
	"main_region.SmartTrafficLightSystem.ActuatorComponent.off",
	"main_region.SmartTrafficLightSystem.ControllerComponent._Initialize_Controller_Component_",
	"main_region.SmartTrafficLightSystem.ControllerComponent._Initialize_Controller_Component_.updating._Controller_Updates_",
	"main_region.SmartTrafficLightSystem.ControllerComponent.off",
	"main_region.SmartTrafficLightSystem.SensorComponent._Initialize_Sensor_Component_",
	"main_region.SmartTrafficLightSystem.SensorComponent._Initialize_Sensor_Component_.updating._Sensor_Updates_",
	"main_region.SmartTrafficLightSystem.SensorComponent.off",
	"main_region.SmartTrafficLightSystem.WiFiGateway._Initialize_WiFi_Component_",
	"main_region.SmartTrafficLightSystem.WiFiGateway._Initialize_WiFi_Component_.updating._WiFi_Updates_",
	"main_region.SmartTrafficLightSystem.WiFiGateway.off",
	"main_region.SmartTrafficLightSystem.PowerCalculatorComponent._Initialize_Power_Component_",
	"main_region.SmartTrafficLightSystem.PowerCalculatorComponent._Initialize_Power_Component_.updating._Power_Updates_",
	"main_region.SmartTrafficLightSystem.PowerCalculatorComponent.off",
	"main_region.SmartTrafficLightSystem.trackingDeviceTemperature._Initialize_DeviceTemp_Component_",
	"main_region.SmartTrafficLightSystem.trackingDeviceTemperature._Initialize_DeviceTemp_Component_.updating._Temperature_Updates_",
	"main_region.SmartTrafficLightSystem.trackingDeviceTemperature.off"
};
