/** Generated by itemis CREATE code generator. */

#ifndef SMARTLIGHTSYSTEM1_META_H_
#define SMARTLIGHTSYSTEM1_META_H_

#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern sc_string SmartLightSystem1_meta_feature_names[];

extern sc_string SmartLightSystem1_meta_state_names[];

#ifdef __cplusplus
}
#endif

#endif /* SMARTLIGHTSYSTEM1_META_H_ */
