/** Generated by itemis CREATE code generator. */

#ifndef SMARTTRAFFICLIGHTSYSTEM_META_H_
#define SMARTTRAFFICLIGHTSYSTEM_META_H_

#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern sc_string SmartTrafficLightSystem_meta_feature_names[];

extern sc_string SmartTrafficLightSystem_meta_state_names[];

#ifdef __cplusplus
}
#endif

#endif /* SMARTTRAFFICLIGHTSYSTEM_META_H_ */
