/** Generated by itemis CREATE code generator. */

#ifndef SMARTMICROWAVESYSTEM_META_H_
#define SMARTMICROWAVESYSTEM_META_H_

#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern sc_string SmartMicrowaveSystem_meta_feature_names[];

extern sc_string SmartMicrowaveSystem_meta_state_names[];

#ifdef __cplusplus
}
#endif

#endif /* SMARTMICROWAVESYSTEM_META_H_ */
