/** Generated by itemis CREATE code generator. */


#ifndef SMARTTVSYSTEMTRACER_H_
#define SMARTTVSYSTEMTRACER_H_


#include "../src/yet_sc_tracer.h"


#include "SmartTVSystem.h"
#include "SmartTVSystem_meta.h"


#ifdef __cplusplus
extern "C"
{
#endif


extern void smartTVSystem_init_sc_tracer(yet_sc_tracer *tracer, SmartTVSystem* machine, sc_string name);


#ifdef __cplusplus
}
#endif


#endif /* SMARTTVSYSTEMTRACER_H_ */
