/** Generated by itemis CREATE code generator. */


#ifndef SMARTMICROWAVESYSTEM1TRACER_H_
#define SMARTMICROWAVESYSTEM1TRACER_H_


#include "../src/yet_sc_tracer.h"


#include "SmartMicrowaveSystem1.h"
#include "SmartMicrowaveSystem1_meta.h"


#ifdef __cplusplus
extern "C"
{
#endif


extern void smartMicrowaveSystem1_init_sc_tracer(yet_sc_tracer *tracer, SmartMicrowaveSystem1* machine, sc_string name);


#ifdef __cplusplus
}
#endif


#endif /* SMARTMICROWAVESYSTEM1TRACER_H_ */
