/** Generated by itemis CREATE code generator. */

#ifndef SMARTTVSYSTEM1_META_H_
#define SMARTTVSYSTEM1_META_H_

#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern sc_string SmartTVSystem1_meta_feature_names[];

extern sc_string SmartTVSystem1_meta_state_names[];

#ifdef __cplusplus
}
#endif

#endif /* SMARTTVSYSTEM1_META_H_ */
