/** Generated by itemis CREATE code generator. */

#include "TrafficLight_Unit_meta.h"
		
sc_string TrafficLight_Unit_meta_feature_names[] = {
	"<nothing>",
	"on",
	"off",
	"device.crossingButton_triggered",
	"device.isOn",
	"Light.color",
	"Light.pedestrian",
	"Light.red",
	"Light.yellow",
	"Light.green",
	"Timer.reset",
	"Timer.counter",
	"Timer.green_period",
	"Timer.red_period",
	"local_Light_yellow",
	"local_Light_green",
	"local_Light_red",
	"local_Timer_reset"
};

sc_string TrafficLight_Unit_meta_state_names[] = {
	"<nostate>",
	"_TrafficLight_Unit_.Off",
	"_TrafficLight_Unit_.On",
	"_TrafficLight_Unit_.On.TrafficLight_Color.Green",
	"_TrafficLight_Unit_.On.TrafficLight_Color.Red",
	"_TrafficLight_Unit_.On.TrafficLight_Color.Yellow",
	"_TrafficLight_Unit_.On.PedestrianLight_Color.StopHand",
	"_TrafficLight_Unit_.On.PedestrianLight_Color.BlinkingWalkingMan",
	"_TrafficLight_Unit_.On.PedestrianLight_Color.WalkingMan",
	"_TrafficLight_Unit_.On.Timer._timer_running_",
	"_TrafficLight_Unit_.On.Timer._timer_running_._Timer_Countdown_._green_period_",
	"_TrafficLight_Unit_.On.Timer._timer_running_._Timer_Countdown_._red_period_",
	"_TrafficLight_Unit_.On.Timer._timer_running_._Timer_Countdown_._yellow_period_",
	"_TrafficLight_Unit_.On.Timer._timer_running_._Timer_Countdown_._final_"
};
