/** Generated by itemis CREATE code generator. */

#ifndef TV_UNIT_META_H_
#define TV_UNIT_META_H_

#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern sc_string TV_Unit_meta_feature_names[];

extern sc_string TV_Unit_meta_state_names[];

#ifdef __cplusplus
}
#endif

#endif /* TV_UNIT_META_H_ */
