/** Generated by itemis CREATE code generator. */
package smarthub.java;

import com.yakindu.core.IEventDriven;
import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import smarthub.java.Actuator_Component;
import smarthub.java.Controller_Component;
import smarthub.java.DeviceTemp_Component;
import smarthub.java.Microwave_Unit;
import smarthub.java.Network_Component;
import smarthub.java.Power_Component;
import smarthub.java.Sensor_Component;

public class SmartMicrowaveSystem implements ITimed, IEventDriven {
	public static class System {
		private SmartMicrowaveSystem parent;
		
		public System(SmartMicrowaveSystem parent) {
			this.parent = parent;
		}
		private boolean on;
		
		
		public void raiseOn() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					on = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean off;
		
		
		public void raiseOff() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					off = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean connect_network;
		
		
		public void raiseConnect_network() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					connect_network = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean disconnect_network;
		
		
		public void raiseDisconnect_network() {
			synchronized(parent) {
				parent.inEventQueue.add(() -> {
					disconnect_network = true;
				});
				parent.runCycle();
			}
		}
		
		private boolean isOn;
		
		public synchronized boolean getIsOn() {
			synchronized(parent) {
				return isOn;
			}
		}
		
		public void setIsOn(boolean value) {
			synchronized(parent) {
				this.isOn = value;
			}
		}
		
	}
	
	public static class SensorInput {
		private SmartMicrowaveSystem parent;
		
		public SensorInput(SmartMicrowaveSystem parent) {
			this.parent = parent;
		}
		private long detection_time;
		
		public synchronized long getDetection_time() {
			synchronized(parent) {
				return detection_time;
			}
		}
		
		public void setDetection_time(long value) {
			synchronized(parent) {
				this.detection_time = value;
			}
		}
		
	}
	
	public static class SensorOutput {
		private SmartMicrowaveSystem parent;
		
		public SensorOutput(SmartMicrowaveSystem parent) {
			this.parent = parent;
		}
		private long counter;
		
		public synchronized long getCounter() {
			synchronized(parent) {
				return counter;
			}
		}
		
		public void setCounter(long value) {
			synchronized(parent) {
				this.counter = value;
			}
		}
		
		private boolean activity;
		
		public synchronized boolean getActivity() {
			synchronized(parent) {
				return activity;
			}
		}
		
		public void setActivity(boolean value) {
			synchronized(parent) {
				this.activity = value;
			}
		}
		
	}
	
	protected System system;
	
	protected SensorInput sensorInput;
	
	protected SensorOutput sensorOutput;
	
	public enum State {
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_OFF,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_ON,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT_OFF,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT_OFF,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT_OFF,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT_OFF,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT_OFF,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_,
		_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE_OFF,
		$NULLSTATE$
	};
	
	private final State[] stateVector = new State[7];
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[8];
	
	private BlockingQueue<Runnable> inEventQueue = new LinkedBlockingQueue<Runnable>();
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		synchronized(SmartMicrowaveSystem.this) {
			return isExecuting;
		}
	}
	
	protected void setIsExecuting(boolean value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.isExecuting = value;
		}
	}
	private long stateConfVectorPosition;
	
	protected long getStateConfVectorPosition() {
		synchronized(SmartMicrowaveSystem.this) {
			return stateConfVectorPosition;
		}
	}
	
	protected void setStateConfVectorPosition(long value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.stateConfVectorPosition = value;
		}
	}
	public SmartMicrowaveSystem() {
		system = new System(this);
		sensorInput = new SensorInput(this);
		sensorOutput = new SensorOutput(this);
		for (int i = 0; i < 7; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		setActuator(null);
		
		setController(null);
		
		setSensor(null);
		
		setWiFi(null);
		
		setPower(null);
		
		setTemp(null);
		
		setMW(null);
		
		setMessage("");
		
		setWiFi_connection(false);
		
		setTemp_value(50l);
		
		setPower_input(10l);
		
		setPower_total(0l);
		
		setPower_required(10l);
		
		system.setIsOn(false);
		
		sensorInput.setDetection_time(50l);
		
		sensorOutput.setCounter(0l);
		
		sensorOutput.setActivity(false);
		
		isExecuting = false;
	}
	
	public synchronized void enter() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		enterSequence__SmartMicrowaveSystem__default();
		isExecuting = false;
	}
	
	public synchronized void exit() {
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		exitSequence__SmartMicrowaveSystem_();
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$||stateVector[1] != State.$NULLSTATE$||stateVector[2] != State.$NULLSTATE$||stateVector[3] != State.$NULLSTATE$||stateVector[4] != State.$NULLSTATE$||stateVector[5] != State.$NULLSTATE$||stateVector[6] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	private void clearInEvents() {
		system.on = false;
		system.off = false;
		system.connect_network = false;
		system.disconnect_network = false;
		timeEvents[0] = false;
		timeEvents[1] = false;
		timeEvents[2] = false;
		timeEvents[3] = false;
		timeEvents[4] = false;
		timeEvents[5] = false;
		timeEvents[6] = false;
		timeEvents[7] = false;
	}
	
	private void microStep() {
		long transitioned = -1l;
		
		stateConfVectorPosition = 0l;
		
		switch (stateVector[0]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_OFF:
			transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_off_react(transitioned);
			break;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_ON:
			transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on_react(transitioned);
			break;
		default:
			break;
		}
		
		if (getStateConfVectorPosition()<1l) {
			switch (stateVector[1]) {
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_:
				transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates__react(transitioned);
				break;
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_:
				transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning__react(transitioned);
				break;
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT_OFF:
				transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<2l) {
			switch (stateVector[2]) {
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_:
				transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates__react(transitioned);
				break;
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT_OFF:
				transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<3l) {
			switch (stateVector[3]) {
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_:
				transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates__react(transitioned);
				break;
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT_OFF:
				transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<4l) {
			switch (stateVector[4]) {
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_:
				transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates__react(transitioned);
				break;
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT_OFF:
				transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<5l) {
			switch (stateVector[5]) {
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_:
				transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates__react(transitioned);
				break;
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT_OFF:
				transitioned = _SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off_react(transitioned);
				break;
			default:
				break;
			}
		}
		if (getStateConfVectorPosition()<6l) {
			switch (stateVector[6]) {
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_:
				_SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates__react(transitioned);
				break;
			case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE_OFF:
				_SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_off_react(transitioned);
				break;
			default:
				break;
			}
		}
	}
	
	private void runCycle() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		nextEvent();
		do { 
			microStep();
			
			clearInEvents();
		} while (nextEvent());
		
		isExecuting = false;
	}
	
	protected boolean nextEvent() {
		if(!inEventQueue.isEmpty()) {
			inEventQueue.poll().run();
			return true;
		}
		return false;
	}
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM:
			return stateVector[0].ordinal() >= State.
					_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM.ordinal()&& stateVector[0].ordinal() <= State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE_OFF.ordinal();
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_OFF:
			return stateVector[0] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_OFF;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_ON:
			return stateVector[0] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_ON;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_:
			return stateVector[1] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_:
			return stateVector[1] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT_OFF:
			return stateVector[1] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT_OFF;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT_:
			return stateVector[2].ordinal() >= State.
					_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT_.ordinal()&& stateVector[2].ordinal() <= State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_.ordinal();
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_:
			return stateVector[2] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT_OFF:
			return stateVector[2] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT_OFF;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT_:
			return stateVector[3].ordinal() >= State.
					_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT_.ordinal()&& stateVector[3].ordinal() <= State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_.ordinal();
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_:
			return stateVector[3] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT_OFF:
			return stateVector[3] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT_OFF;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT_:
			return stateVector[4].ordinal() >= State.
					_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT_.ordinal()&& stateVector[4].ordinal() <= State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_.ordinal();
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_:
			return stateVector[4] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT_OFF:
			return stateVector[4] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT_OFF;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT_:
			return stateVector[5].ordinal() >= State.
					_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT_.ordinal()&& stateVector[5].ordinal() <= State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_.ordinal();
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_:
			return stateVector[5] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT_OFF:
			return stateVector[5] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT_OFF;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT_:
			return stateVector[6].ordinal() >= State.
					_SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT_.ordinal()&& stateVector[6].ordinal() <= State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_.ordinal();
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_:
			return stateVector[6] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE_OFF:
			return stateVector[6] == State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE_OFF;
		default:
			return false;
		}
	}
	
	public synchronized void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public synchronized void raiseTimeEvent(int eventID) {
		inEventQueue.add(() -> {
			timeEvents[eventID] = true;
		});
		runCycle();
	}
	
	public System system() {
		return system;
	}
	
	public SensorInput sensorInput() {
		return sensorInput;
	}
	
	public SensorOutput sensorOutput() {
		return sensorOutput;
	}
	
	
	private Actuator_Component actuator;
	
	public synchronized Actuator_Component getActuator() {
		synchronized(SmartMicrowaveSystem.this) {
			return actuator;
		}
	}
	
	public void setActuator(Actuator_Component value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.actuator = value;
		}
	}
	
	private Controller_Component controller;
	
	public synchronized Controller_Component getController() {
		synchronized(SmartMicrowaveSystem.this) {
			return controller;
		}
	}
	
	public void setController(Controller_Component value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.controller = value;
		}
	}
	
	private Sensor_Component sensor;
	
	public synchronized Sensor_Component getSensor() {
		synchronized(SmartMicrowaveSystem.this) {
			return sensor;
		}
	}
	
	public void setSensor(Sensor_Component value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.sensor = value;
		}
	}
	
	private Network_Component wiFi;
	
	public synchronized Network_Component getWiFi() {
		synchronized(SmartMicrowaveSystem.this) {
			return wiFi;
		}
	}
	
	public void setWiFi(Network_Component value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.wiFi = value;
		}
	}
	
	private Power_Component power;
	
	public synchronized Power_Component getPower() {
		synchronized(SmartMicrowaveSystem.this) {
			return power;
		}
	}
	
	public void setPower(Power_Component value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.power = value;
		}
	}
	
	private DeviceTemp_Component temp;
	
	public synchronized DeviceTemp_Component getTemp() {
		synchronized(SmartMicrowaveSystem.this) {
			return temp;
		}
	}
	
	public void setTemp(DeviceTemp_Component value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.temp = value;
		}
	}
	
	private Microwave_Unit mW;
	
	public synchronized Microwave_Unit getMW() {
		synchronized(SmartMicrowaveSystem.this) {
			return mW;
		}
	}
	
	public void setMW(Microwave_Unit value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.mW = value;
		}
	}
	
	private String message;
	
	public synchronized String getMessage() {
		synchronized(SmartMicrowaveSystem.this) {
			return message;
		}
	}
	
	public void setMessage(String value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.message = value;
		}
	}
	
	private boolean wiFi_connection;
	
	public synchronized boolean getWiFi_connection() {
		synchronized(SmartMicrowaveSystem.this) {
			return wiFi_connection;
		}
	}
	
	public void setWiFi_connection(boolean value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.wiFi_connection = value;
		}
	}
	
	private long temp_value;
	
	public synchronized long getTemp_value() {
		synchronized(SmartMicrowaveSystem.this) {
			return temp_value;
		}
	}
	
	public void setTemp_value(long value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.temp_value = value;
		}
	}
	
	private long power_input;
	
	public synchronized long getPower_input() {
		synchronized(SmartMicrowaveSystem.this) {
			return power_input;
		}
	}
	
	public void setPower_input(long value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.power_input = value;
		}
	}
	
	private long power_total;
	
	public synchronized long getPower_total() {
		synchronized(SmartMicrowaveSystem.this) {
			return power_total;
		}
	}
	
	public void setPower_total(long value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.power_total = value;
		}
	}
	
	private long power_required;
	
	public synchronized long getPower_required() {
		synchronized(SmartMicrowaveSystem.this) {
			return power_required;
		}
	}
	
	public void setPower_required(long value) {
		synchronized(SmartMicrowaveSystem.this) {
			this.power_required = value;
		}
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_off() {
		system.setIsOn(false);
		
		getPower().raiseOff();
		
		getSensor().raiseOff();
		
		getMW().device().raiseOff();
		
		system.raiseConnect_network();
		
		mW.setIn_use(false);
	}
	
	/* Entry action for state 'on'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on() {
		timerService.setTimer(this, 0, 1000l, false);
		
		system.setIsOn(true);
		
		getPower().raiseOn();
		
		getSensor().raiseOn();
		
		getMW().device().raiseOn();
	}
	
	/* Entry action for state '<Actuator_Updates>'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates_() {
		timerService.setTimer(this, 1, 500l, false);
		
		actuator.power().setDeviceInput(power_input);
		
		mW.setFood_inside_sensed(actuator.getIsTriggered());
	}
	
	/* Entry action for state '<Device_Functioning>'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning_() {
		timerService.setTimer(this, 2, (1l * 1000l), true);
		
		if (getActuator().device().getActuated()) {
			setMessage("Smart devices main function is here");
		}
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off() {
		getActuator().raiseOff();
		
		actuator.power().setRequired(power_required);
	}
	
	/* Entry action for state '<Controller_Updates>'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_() {
		timerService.setTimer(this, 3, 500l, false);
		
		controller.sensors().setTriggered(sensorOutput.activity);
		
		controller.setActivity(sensorOutput.activity);
		
		actuator.setIsTriggered(controller.actuator().getTriggered());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off() {
		getController().raiseOff();
	}
	
	/* Entry action for state '<Sensor_Updates>'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_() {
		timerService.setTimer(this, 4, 500l, false);
		
		sensor.setSimulate_detection_timer(sensorInput.detection_time);
		
		sensorOutput.setActivity(sensor.getActivity());
		
		sensorOutput.setCounter(sensor.getCounter());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off() {
		getSensor().raiseOff();
	}
	
	/* Entry action for state '<WiFi_Updates>'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_() {
		timerService.setTimer(this, 5, 500l, false);
		
		setWiFi_connection(wiFi.getConnection());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_off() {
		getWiFi().raiseOff();
	}
	
	/* Entry action for state '<Power_Updates>'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_() {
		timerService.setTimer(this, 6, 500l, false);
		
		power.device().setIsOn(system.isOn);
		
		power.setKilowatt(power_input);
		
		setPower_total(power.getKWh());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off() {
		getPower().raiseOff();
	}
	
	/* Entry action for state '<Temperature_Updates>'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_() {
		timerService.setTimer(this, 7, 500l, false);
		
		setTemp_value(temp.heat().getLevel());
	}
	
	/* Entry action for state 'off'. */
	private void entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_off() {
		temp.device().setIsOn(system.isOn);
	}
	
	/* Exit action for state 'on'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on() {
		timerService.unsetTimer(this, 0);
	}
	
	/* Exit action for state '<Actuator_Updates>'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates_() {
		timerService.unsetTimer(this, 1);
	}
	
	/* Exit action for state '<Device_Functioning>'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning_() {
		timerService.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off() {
		getActuator().raiseOn();
	}
	
	/* Exit action for state '<Controller_Updates>'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_() {
		timerService.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off() {
		getController().raiseOn();
	}
	
	/* Exit action for state '<Sensor_Updates>'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_() {
		timerService.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off() {
		getSensor().raiseOn();
	}
	
	/* Exit action for state '<WiFi_Updates>'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_() {
		timerService.unsetTimer(this, 5);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_off() {
		getWiFi().raiseOn();
	}
	
	/* Exit action for state '<Power_Updates>'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_() {
		timerService.unsetTimer(this, 6);
	}
	
	/* Exit action for state 'off'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off() {
		getPower().raiseOn();
	}
	
	/* Exit action for state '<Temperature_Updates>'. */
	private void exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_() {
		timerService.unsetTimer(this, 7);
	}
	
	/* 'default' enter sequence for state SmartMicrowaveSystem */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_default();
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_default();
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_default();
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_default();
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_default();
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_default();
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_default();
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_off_default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_off();
		stateVector[0] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_OFF;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state on */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on_default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on();
		stateVector[0] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_ON;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state <Actuator_Updates> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates__default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates_();
		stateVector[1] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state <Device_Functioning> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning__default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning_();
		stateVector[1] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off_default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off();
		stateVector[1] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT_OFF;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state <Initialize_Controller_Component> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating_default();
	}
	
	/* 'default' enter sequence for state <Controller_Updates> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates__default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_();
		stateVector[2] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off_default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off();
		stateVector[2] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT_OFF;
		stateConfVectorPosition = 2;
	}
	
	/* 'default' enter sequence for state <Initialize_Sensor_Component> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating_default();
	}
	
	/* 'default' enter sequence for state <Sensor_Updates> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates__default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_();
		stateVector[3] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off_default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off();
		stateVector[3] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT_OFF;
		stateConfVectorPosition = 3;
	}
	
	/* 'default' enter sequence for state <Initialize_WiFi_Component> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating_default();
	}
	
	/* 'default' enter sequence for state <WiFi_Updates> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates__default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_();
		stateVector[4] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_;
		stateConfVectorPosition = 4;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_off_default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_off();
		stateVector[4] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT_OFF;
		stateConfVectorPosition = 4;
	}
	
	/* 'default' enter sequence for state <Initialize_Power_Component> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating_default();
	}
	
	/* 'default' enter sequence for state <Power_Updates> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates__default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_();
		stateVector[5] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_;
		stateConfVectorPosition = 5;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off_default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off();
		stateVector[5] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT_OFF;
		stateConfVectorPosition = 5;
	}
	
	/* 'default' enter sequence for state <Initialize_DeviceTemp_Component> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating_default();
	}
	
	/* 'default' enter sequence for state <Temperature_Updates> */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates__default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_();
		stateVector[6] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_;
		stateConfVectorPosition = 6;
	}
	
	/* 'default' enter sequence for state off */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_off_default() {
		entryAction__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_off();
		stateVector[6] = State._SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE_OFF;
		stateConfVectorPosition = 6;
	}
	
	/* 'default' enter sequence for region <SmartMicrowaveSystem> */
	private void enterSequence__SmartMicrowaveSystem__default() {
		react__SmartMicrowaveSystem___entry_Default();
	}
	
	/* 'default' enter sequence for region SystemStatus */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus__entry_Default();
	}
	
	/* 'default' enter sequence for region ActuatorComponent */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region ControllerComponent */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region updating */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__entry_Default();
	}
	
	/* 'default' enter sequence for region SensorComponent */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region updating */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__entry_Default();
	}
	
	/* 'default' enter sequence for region NetworkComponent */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region updating */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__entry_Default();
	}
	
	/* 'default' enter sequence for region PowerCalculatorComponent */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__entry_Default();
	}
	
	/* 'default' enter sequence for region updating */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__entry_Default();
	}
	
	/* 'default' enter sequence for region trackingDeviceTemperature */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__entry_Default();
	}
	
	/* 'default' enter sequence for region updating */
	private void enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating_default() {
		react__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__entry_Default();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_off() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state on */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on() {
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on();
	}
	
	/* Default exit sequence for state <Actuator_Updates> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates_() {
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates_();
	}
	
	/* Default exit sequence for state <Device_Functioning> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning_() {
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off() {
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off();
	}
	
	/* Default exit sequence for state <Initialize_Controller_Component> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component_() {
		exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating();
	}
	
	/* Default exit sequence for state <Controller_Updates> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_() {
		stateVector[2] = State.$NULLSTATE$;
		stateConfVectorPosition = 2;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off() {
		stateVector[2] = State.$NULLSTATE$;
		stateConfVectorPosition = 2;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off();
	}
	
	/* Default exit sequence for state <Initialize_Sensor_Component> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component_() {
		exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating();
	}
	
	/* Default exit sequence for state <Sensor_Updates> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_() {
		stateVector[3] = State.$NULLSTATE$;
		stateConfVectorPosition = 3;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off() {
		stateVector[3] = State.$NULLSTATE$;
		stateConfVectorPosition = 3;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off();
	}
	
	/* Default exit sequence for state <Initialize_WiFi_Component> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component_() {
		exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating();
	}
	
	/* Default exit sequence for state <WiFi_Updates> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_() {
		stateVector[4] = State.$NULLSTATE$;
		stateConfVectorPosition = 4;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_off() {
		stateVector[4] = State.$NULLSTATE$;
		stateConfVectorPosition = 4;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_off();
	}
	
	/* Default exit sequence for state <Initialize_Power_Component> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component_() {
		exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating();
	}
	
	/* Default exit sequence for state <Power_Updates> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_() {
		stateVector[5] = State.$NULLSTATE$;
		stateConfVectorPosition = 5;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off() {
		stateVector[5] = State.$NULLSTATE$;
		stateConfVectorPosition = 5;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off();
	}
	
	/* Default exit sequence for state <Initialize_DeviceTemp_Component> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component_() {
		exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating();
	}
	
	/* Default exit sequence for state <Temperature_Updates> */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_() {
		stateVector[6] = State.$NULLSTATE$;
		stateConfVectorPosition = 6;
		
		exitAction__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_();
	}
	
	/* Default exit sequence for state off */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_off() {
		stateVector[6] = State.$NULLSTATE$;
		stateConfVectorPosition = 6;
	}
	
	/* Default exit sequence for region <SmartMicrowaveSystem> */
	private void exitSequence__SmartMicrowaveSystem_() {
		switch (stateVector[0]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_OFF:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_off();
			break;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SYSTEMSTATUS_ON:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on();
			break;
		default:
			break;
		}
		
		switch (stateVector[1]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__ACTUATOR_UPDATES_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates_();
			break;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT__DEVICE_FUNCTIONING_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning_();
			break;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_ACTUATORCOMPONENT_OFF:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off();
			break;
		default:
			break;
		}
		
		switch (stateVector[2]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_();
			break;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT_OFF:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off();
			break;
		default:
			break;
		}
		
		switch (stateVector[3]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_();
			break;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT_OFF:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off();
			break;
		default:
			break;
		}
		
		switch (stateVector[4]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_();
			break;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT_OFF:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_off();
			break;
		default:
			break;
		}
		
		switch (stateVector[5]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_();
			break;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT_OFF:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off();
			break;
		default:
			break;
		}
		
		switch (stateVector[6]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_();
			break;
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE_OFF:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_off();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region updating */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating() {
		switch (stateVector[2]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_CONTROLLERCOMPONENT__INITIALIZE_CONTROLLER_COMPONENT__UPDATING__CONTROLLER_UPDATES_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region updating */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating() {
		switch (stateVector[3]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_SENSORCOMPONENT__INITIALIZE_SENSOR_COMPONENT__UPDATING__SENSOR_UPDATES_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region updating */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating() {
		switch (stateVector[4]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_NETWORKCOMPONENT__INITIALIZE_WIFI_COMPONENT__UPDATING__WIFI_UPDATES_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region updating */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating() {
		switch (stateVector[5]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_POWERCALCULATORCOMPONENT__INITIALIZE_POWER_COMPONENT__UPDATING__POWER_UPDATES_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region updating */
	private void exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating() {
		switch (stateVector[6]) {
		case _SMARTMICROWAVESYSTEM__SMARTMICROWAVESYSTEM_TRACKINGDEVICETEMPERATURE__INITIALIZE_DEVICETEMP_COMPONENT__UPDATING__TEMPERATURE_UPDATES_:
			exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus__entry_Default() {
		getMW().enter();
		
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__entry_Default() {
		getActuator().enter();
		
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__entry_Default() {
		getController().enter();
		
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__entry_Default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__entry_Default() {
		getSensor().enter();
		
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__entry_Default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__entry_Default() {
		getWiFi().enter();
		
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__entry_Default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__entry_Default() {
		getPower().enter();
		
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__entry_Default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__entry_Default() {
		getTemp().enter();
		
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_off_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__entry_Default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates__default();
	}
	
	/* Default react sequence for initial entry  */
	private void react__SmartMicrowaveSystem___entry_Default() {
		enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_default();
	}
	
	private long react(long transitioned_before) {
		return transitioned_before;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		transitioned_after = react(transitioned_before);
		
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_off_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0l) {
			if (system.on) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_off();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<0l) {
			if (system.off) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_off_default();
				transitioned_after = 0l;
			} else {
				if (timeEvents[0]) {
					exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on();
					timeEvents[0] = false;
					enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SystemStatus_on_default();
					transitioned_after = 0l;
				}
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<1l) {
			if (getActuator().getIsTriggered()) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates_();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning__default();
				transitioned_after = 1l;
			} else {
				if (system.off) {
					exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates_();
					enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off_default();
					transitioned_after = 1l;
				} else {
					if (timeEvents[1]) {
						exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates_();
						timeEvents[1] = false;
						enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates__default();
						transitioned_after = 1l;
					}
				}
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<1l) {
			if (!getActuator().getIsTriggered()) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning_();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates__default();
				transitioned_after = 1l;
			} else {
				if (system.off) {
					exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Device_Functioning_();
					enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off_default();
					transitioned_after = 1l;
				}
			}
		}
		if (transitioned_after==transitioned_before) {
			if (timeEvents[2]) {
				mW.setFood_inside_sensed(actuator.getIsTriggered());
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<1l) {
			if (system.on) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent_off();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ActuatorComponent__Actuator_Updates__default();
				transitioned_after = 1l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<2l) {
			if (system.off) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component_();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off_default();
				transitioned_after = 2l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<2l) {
			if (timeEvents[3]) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates_();
				timeEvents[3] = false;
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__updating__Controller_Updates__default();
				_SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__react(2l);
				
				transitioned_after = 2l;
			}
		}
		if (transitioned_after==transitioned_before) {
			transitioned_after = _SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<2l) {
			if (system.on) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent_off();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_ControllerComponent__Initialize_Controller_Component__default();
				transitioned_after = 2l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<3l) {
			if (system.off) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component_();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off_default();
				transitioned_after = 3l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<3l) {
			if (timeEvents[4]) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates_();
				timeEvents[4] = false;
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__updating__Sensor_Updates__default();
				_SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__react(3l);
				
				transitioned_after = 3l;
			}
		}
		if (transitioned_after==transitioned_before) {
			transitioned_after = _SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<3l) {
			if (system.on) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent_off();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_SensorComponent__Initialize_Sensor_Component__default();
				transitioned_after = 3l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<4l) {
			if ((system.off || system.disconnect_network)) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component_();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_off_default();
				transitioned_after = 4l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<4l) {
			if (timeEvents[5]) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates_();
				timeEvents[5] = false;
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__updating__WiFi_Updates__default();
				_SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__react(4l);
				
				transitioned_after = 4l;
			}
		}
		if (transitioned_after==transitioned_before) {
			transitioned_after = _SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_off_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<4l) {
			if ((system.on || system.connect_network)) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent_off();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_NetworkComponent__Initialize_WiFi_Component__default();
				transitioned_after = 4l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<5l) {
			if (system.off) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component_();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off_default();
				transitioned_after = 5l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<5l) {
			if (timeEvents[6]) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates_();
				timeEvents[6] = false;
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__updating__Power_Updates__default();
				_SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__react(5l);
				
				transitioned_after = 5l;
			}
		}
		if (transitioned_after==transitioned_before) {
			transitioned_after = _SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<5l) {
			if (system.on) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent_off();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_PowerCalculatorComponent__Initialize_Power_Component__default();
				transitioned_after = 5l;
			}
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<6l) {
			if (system.off) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component_();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_off_default();
				_SmartMicrowaveSystem__SmartMicrowaveSystem_react(0l);
				
				transitioned_after = 6l;
			}
		}
		if (transitioned_after==transitioned_before) {
			transitioned_after = _SmartMicrowaveSystem__SmartMicrowaveSystem_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates__react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<6l) {
			if (timeEvents[7]) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates_();
				timeEvents[7] = false;
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__updating__Temperature_Updates__default();
				_SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__react(6l);
				
				transitioned_after = 6l;
			}
		}
		if (transitioned_after==transitioned_before) {
			transitioned_after = _SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__react(transitioned_before);
		}
		return transitioned_after;
	}
	
	private long _SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_off_react(long transitioned_before) {
		long transitioned_after = transitioned_before;
		
		if (transitioned_after<6l) {
			if (system.on) {
				exitSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature_off();
				enterSequence__SmartMicrowaveSystem__SmartMicrowaveSystem_trackingDeviceTemperature__Initialize_DeviceTemp_Component__default();
				_SmartMicrowaveSystem__SmartMicrowaveSystem_react(0l);
				
				transitioned_after = 6l;
			}
		}
		if (transitioned_after==transitioned_before) {
			transitioned_after = _SmartMicrowaveSystem__SmartMicrowaveSystem_react(transitioned_before);
		}
		return transitioned_after;
	}
	
	/* Can be used by the client code to trigger a run to completion step without raising an event. */
	public synchronized void triggerWithoutEvent() {
		runCycle();
	}
}
